### ISSUE TITLE
4.46 - SystemPath from prior qualifying exits  (QC Error 192)

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#102]
We have a client in sys_Enrollment for prior qualifying exit with 2 enrollments; one for street outreach and the other for ES night by night.  In section 4.46 on the last pass for setting system update, the system path is being set as 1 because the ptype summary is returning only 1 and not caring about street outreach.  

Thus in the lsa person, his exitFrom = 1 (Street Outreach) is being set with a system path of 1 (ES/SH) which is being flagged.  The flag states that this should be a 12 for anyone with an ExitFrom 1 (Street outreach).

Should that ptype summary statement take into account sys_Enrollment records that contain project type street outreach?  

Also, should the population of sys_Enrollment in 4.46 take into account LSA_Project in the table joins?

Here is the results of what I'm seeing:  The top image is what the case when has to work with.  The bottom image is what the ptype subquery is returning.
![image](https://user-images.githubusercontent.com/44415627/55120028-48658100-50c2-11e9-9f4f-132723bf9333.png)

**Comment by nathanandrade74** [comment]
We are also getting this flag along with others related to it, I believe that the order that the queries are run for this section may be causing many of the problems. The fourth query in section 4.46 should set systemPath = 12 for all records where ExitFrom =1. This query joins tmp_exit (which includes records from all cohorts) on sys_enrollment, however at this point sys_enrollment has not yet been emptied and reloaded, so only enrollments that are active in the reporting period are currently included in sys_enrollment. Because of this, only records in tmp_exit that are active in the reporting period will be updated by this query. I believe if this query is moved to execute after the query where sys_enrollment is reloaded, then that should correct many of the related flags.

**Comment by jbloescw** [comment]
I agree.  I moved the 

`
update ex
SET ex.SystemPath = CASE 
	WHEN ex.ExitFrom = 1 THEN 12
	WHEN ex.ExitFrom = 2 THEN 1
	WHEN ex.ExitFrom = 3 THEN 2
	WHEN ex.ExitFrom = 4 THEN 1
	WHEN ex.ExitFrom = 5 THEN 4
	WHEN ex.ExitFrom = 6 THEN 8
	ELSE 8 END
--Select * 
FROM #tmp_Exit ex 
    INNER JOIN #sys_Enrollment sn 
	   ON sn.EnrollmentID = ex.EnrollmentID
	   and ex.HoHID = 18460
    INNER JOIN #tmp_CohortDates cd 
	   ON cd.Cohort = ex.Cohort
WHERE ex.SystemPath IS NULL
	AND (ex.Stat IN (1,2,3,4) OR ex.ExitFrom = 1)`


To right before the last SystemPath setting update after all the sys_Enrollment was reloaded and it is assigning the correct SystemPath value now.

**Comment by eanders** [comment]
@jbloescw any chance you would share your changes via pull request?  It'd be great if we didn't all have to implement these, or wait for Molly, and that might give Molly a starting point for implementing the changes.

**Comment by jbloescw** [comment]
@eanders my GitHub game is not strong so I'm unsure how to go about that.
In my test, i moved lines in the HUD sample code 3345 - 3362 to right before line 3474.
I have not committed anything yet in case there is some other intent of it accessing sys_Enrollment data before being purged and reloaded with the prior qualifying exit data.

**Comment by eanders** [comment]
Thanks @jbloescw.  If you are up for creating a pull request, just commit the changes to your fork (https://github.com/jbloescw/LSASampleCode) and push them with `git push`, either on the master branch or another.  Then visit this page: https://github.com/HMIS/LSASampleCode/compare and click "compare across forks."  Then you can choose your fork and branch and click the "Create Pull Request" button.

**Comment by eanders** [comment]
We believe this will also fix 193, 194, 195, 196.
