### ISSUE TITLE
4.59-4.63 Check ref_Population joins against specs for lp.Age vs. an.AgeGroup

### ISSUE THREAD

**Issue by MollyMcEvilley** [abtassociates/LSASampleCode#111]
Related to DQ flags •	25531, 25534, 25537, 25540, 25543, 25552, 25555, 25686, 25698, 25701, 25835, 25838, 25842, 25844, 25847, 25850, 25853, 25856, 25996, 26382, 26605, 26608, 26611, 26614, 26617, 26626, 26629,26632, 26762, 26765, 26771, 26774, 26777, 26907, 26908, 26910, 26913, 26916, 26923, 26925, 26931, 26934

**Comment by MollyMcEvilley** [comment]
(Similar Flags: 25832, 25844, 25842, 25698, 25701, 25528, 25537, 25540, 25552, 25555)

**Comment by eanders** [comment]
@MollyMcEvilley should this be implemented for 4.62 as well?  We're seeing the following that would indicate a difference in how age is being calculated between the two.

![Screen Shot 2019-06-03 at 1 42 27 PM](https://user-images.githubusercontent.com/1346876/58822435-81136080-8605-11e9-9e15-4a7f85454420.png)
.

These are showing up as QC flags 15568, 15588.

**Comment by eanders** [comment]
Notes for the future:
A chronically homeless household may contain non-chronically homeless adults.  Because the chronically homeless nature of the household is stored in LSA Person, it is not necessarily accurate on any given date. 

In the above scenario, the non-chronically homeless individual may have been enrolled in a different ES project with someone else who is chronically homeless, which could trigger this.
