### ISSUE TITLE
4.7 Setting MoveInDate for active_household

### ISSUE THREAD

**Issue by nathanandrade74** [abtassociates/LSASampleCode#118]
The changes made to section 4.7 included changes to the subquery (starting on line 827) used to find the MoveInDate for the household_id. If a client joins a household after other members of that household have already moved in to housing, then that client will return NULL for this subquery, while other clients who entered into the project before or on the MoveInDate will return the MoveInDate. Since the main query for 4.7 does a SELECT DISTINCT, two rows will be created for this household_id, one with the MoveInDate filled in and one left NULL. Was this the intended outcome for this query?

**Comment by MollyMcEvilley** [comment]
Definitely not the intended outcome.  To simplify this in the sample code, I'm going to remove MoveInDate from the INSERT statement and do an UPDATE for active_Household.MoveInDate after the records are created.

update ahh
set ahh.MoveInDate = hn.MoveInDate
from active_Household ahh
inner join hmis_Enrollment hn on hn.HouseholdID = ahh.HouseholdID 
	and hn.PersonalID = ahh.HoHID and hn.MoveInDate is not null
inner join lsa_Report rpt on rpt.ReportEnd >= hn.MoveInDate  
where ahh.ProjectType in (3,13)
	and hn.MoveInDate >= hn.EntryDate

**Comment by nathanandrade74** [comment]
I believe that this logic change is causing a potential difference between the values for MoveInDate1 and MoveInDate3. Based on the current logic in 4.7, if there is a case where the head of household has a MoveInDate, but leaves before the reporting period, any remaining household members will not have a MoveInDate since none of them will be designated as the HoHID in active_Household. However, when the dq_enrollment table is loaded, the HoH who was previously excluded will now be included in section 4.70 and the household members will be assigned their MoveInDate.

This caused flag ID 224: "The LSAReport field MoveInDate1, which counts the total number of exits (distinct Enrollment IDs among exiters) of heads of household in the report period from RRH or PSH to a permanent housing destination where there was no move-in date within the enrollment entry and exit dates, cannot be greater than MoveInDate3, which counts the same for the three-year period including the report period plus the prior two years."

**Comment by MollyMcEvilley** [comment]
If I'm understanding this correctly, that would be a data issue and not a code issue.  
The HoH must be present for the duration of the household's enrollment.  
If the person designated as the HoH at entry leaves, relationships for household members must be edited so that:
- A member who is there from start to end is the HoH -- and as the HoH, the CoC Code, MoveInDate, and any other data elements associated with the HoH have to be associated with their enrollment.
- Relationship to Head of Household for all household members -- including the original HoH -- must identify their relationship to the new HoH.
