### ISSUE TITLE
4.28.b -- Question about order by case statement

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#129]
Our developers are curious about the statement:
```sql
order by case when an.ExitDate is null then rpt.ReportEnd else an.ExitDate end desc
```
In 4.28.b (and elsewhere).  

Here is their question:
> I wonder if it addresses the scenario when an.ExitDate is after rpt.ReportEnd.

> Here is an example:
> LSA report date range = [1/10/2017 - 30/9/2018]
> Client A has 2 enrollments that meet all criteria from the sql query:
> * Project A enrollment [1/1/2018 - active]
> * Project B enrollment [1/1/2017 - 2/10/2018]

>According to programmed sort rules, "top 1" is Project B enrollment. But why? Both project enrollments were active on [report end date]. In this case, I think we should sort by "EntryDate desc" and Project A enrollment should be "top 1"

![image](https://user-images.githubusercontent.com/6241517/59286933-3eb9d700-8c36-11e9-8c18-3c7d044fbbcb.png)

**Comment by michelleogburn** [comment]
@MollyMcEvilley , this is still an open question for us.

**Comment by MollyMcEvilley** [comment]
The code is doing what you suggest it should BECAUSE it isn't selecting from raw HMIS data but from active_Enrollment -- where the **ExitDate** column will be non-NULL only if the HMIS _ExitDate_ is on or before **ReportEnd**.  

As such, the first sort value for both enrollments is identical (**ReportEnd**), so the record is selected based on most recent _EntryDate_, which is the Project A enrollment. 

This is the code from 4.8 Get Active Enrollments...
https://github.com/HMIS/LSASampleCode/blob/5bd61191abed732a61f7ce57adf718a75af01e36/LSASampleCode.sql#L878-#L910
