### ISSUE TITLE
Data set data issues: Exit.csv has some invalid values

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#156]
In the the sample data with 2020_4_30 in the name, in Exit.csv, there are 5 fields where the value is 99 and it says that is not allowed: 
 DestinationSafeWorker, PosAdultConnections, PosPeerConnections, and PosCommunityConnections all have 99's in some rows and that is not a valid value according to https://files.hudexchange.info/resources/documents/HMIS-Data-Standards-Manual.pdf , p 196, R19

99 does seem like an invalid value for:
DestinationSafeWorker, R19 field 2
PosAdultConnections, R19 field 3
PosPeerConnections, R19 field 4
and PosCommunityConnections R19 field 5

Also in Exit.csv,  CMExitReason Field's value '99' is not a valid 'CMExitReason' value
https://files.hudexchange.info/resources/documents/HMIS-Data-Standards-Manual.pdf p212 see v9, see 99 is indeed not a valid value

If I am interpreting the data standards correctly, might you be able to issue a new data set with these corrections made? Thanks!

**Comment by dburgstrom** [comment]
Hi Michelle, thank you for bringing this up. Those 99 values are included in accordance with paragraphs 3 and 4 of Appendix B of the HMIS CSV specifications:

"The HMIS Data Dictionary explicitly includes a ‘Data not collected’ response for most option list fields.  In addition, the HMIS Data Dictionary  requires that an HMIS must allow users to record ‘Data not collected’ in any field that forces a user to select a value to be able to “move forward in the system.”  Consistent with that requirement, the lists in this document include 99 (Data not collected) as a valid value for some fields defined in the Universal and Program-Specific Data Elements even in cases where it was not specifically included in the HMIS Data Dictionary.  

The ‘Data not collected’ option has not been included and is not considered valid in the HMIS CSV in instances where a record would not exist in the absence of a valid response.  (For example, the list of PATH Services in list 4.14A does not include a ‘Data not collected’ response because a record of a service that does not identify the service is meaningless.)"

Thanks.

**Comment by dburgstrom** [comment]
To expand on my comment, the original reason we had 99's was that export to RHY and VA repositories required a value and not NULL. Are the 99's making it so you cannot import to your system?

**Comment by MichelleNevius** [comment]
Ok, David, thanks, that makes it clear. I am going to ask one of our programmers to handle it here/ remove the validation error from our HMIS's validator. Thanks again!

**Comment by bayboos** [comment]
Hello David. 

To answer your question first: yes, CSV filesets containing unexpected values (meaning: values that are not allowed by the official documents) are rejected by our system. That's a deliberate choice, in an effort to preserve data integrity without expanding the import logic beyond specification.

You are right that HMIS CSV Specification does "include 99 (Data not collected) as a valid value for some fields defined in the Universal and Program-Specific Data Elements even in cases where it was not specifically included in the HMIS Data Dictionary". 

But that does not apply here. All of the fields mentioned by Michelle can be null, and that means the 99 value is not needed to “move forward in the system” in case the actual value is not known. Additionally, neither of those documents states that a value (regardless of what this value would be) may be allowed when it does not appear in any of them. And on top of that, both documents are in full agreement in case of R19 fields. This includes:

R19.2 field using 1.7 list - this list contains 99 value, and that's what we need to investigate further on our end; while
R19 section, fields .3 to .5 using R19.A list - this list does not contain 99 value in neither of those documents.

The same is true for CMExitReason field, using V9.1 list - null value is allowed, and thus 99 value is not needed.

Knowing that, and since neither of those field is actually used for the LSA calculations, it seems reasonable to have null value in fields R19.3, R19.4, R19.5 and V9.1 (PosAdultConnections, PosPeerConnections, PosCommunityConnections and CMExitReason respectively), and maybe even in R19.1 field (DestinationSafeWorker) in the Test Kit Data files - rather than forcing the system to accept values outside of the specification and dictionary.

Thank you for taking the time to read this note; any response will be highly appreciated.

**Comment by dburgstrom** [comment]
Hi Miek. Thank you for letting me know that the values are stopping up your import system. We can remove those 99's and replace them with NULL's.

**Comment by MichelleNevius** [comment]
The 5.8 test data did not produce this error again for us, so I'm going to go ahead and close this issues. Thanks!
