### ISSUE TITLE
Data Set - Client Date Created after Enrollment Date Created

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#159]
@dburgstrom We are finding a problem where the Client Date Created is after the Enrollment Date Created. Here is an example:

Client ID 1782 | Enrollment ID 12340 | Enrollment ID 15790
-----|-----|------
Added 4/10/2018|Added 3/30/2018|Added 3/30/2018
Updated 4/11/2018|Updated 4/10/2018|Updated 11/5/2019

This is affecting more than 10,160 rows that we can't import.

**Comment by dburgstrom** [comment]
Hi Michelle. We can update the client records if it stops your importer.

The data is originally based on real-world HMIS entry, then shuffled a bit to cover some LSA scenarios; so that could either have been caused by unduplication (merging a client into a more-recently created client) or the shifting of dates.

Thanks.

**Comment by michelleogburn** [comment]
@dburgstrom , apologies... yes this needs to be corrected in order for us to import the data. 

Thanks for your efforts.

**Comment by dburgstrom** [comment]
Thanks for the update. It looks like we updated the client-created dates for all of the clients in the test kit so that they fall well before the intake dates. Let me know if this is still an issue for you.

**Comment by michelleogburn** [comment]
Hmm. I'll take a look. Sounded like there was still an issue.

**Comment by michelleogburn** [comment]
This is resolved per our developer.
