### ISSUE TITLE
9.2 The code using different conditions than described in the specs document

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#174]
In the update query, DisablingCond1/3 sub-query, the specification document states that "Status1/Status3 Is not null" condition should be met; however the sameple code does not include it at all. Additionally, the code includes inner join with lsa_report that is not mentioned in the specs (no clear indication why it would be needed in this particular sub-query). Similar issues can be found in various other sub-queries in the same update query.

Please explain or correct. Any input will be highly appreciated.

**Comment by MollyMcEvilley** [comment]
Thanks -- I corrected the code for DisablingCond1 to check for Status1 is not NULL.

In practice, there isn't any need to check for Status3 is not null in the code, because there are no non-NULL values -- all of the enrollments in dq_Enrollment are relevant to three-year reporting -- so I didn't change the code for that, but I did comment the code to explain the discrepancy.
