### ISSUE TITLE
3.5 Issues - tlsa_Enrollment - [ActiveAge] sample code issue

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#193]
Spec
"ActiveAge is calculated **for all enrollments**" (FYI: **active within [10/01/2012 - ReportEnd] including exited before ReportStart**)

![image-20200521-100626](https://user-images.githubusercontent.com/20728145/82619142-fc10b680-9b89-11ea-9b9f-c3e70596865d.png)

Sample Code
Enrollments are limited to still active or exited on or after ReportStart.

So, according to the current code, "n.ExitDate < rpt.ReportStart" is an impossible condition. But the real issue is that no restriction should be applied for `tlsa_Enrollment`.

![image-20200521-100923](https://user-images.githubusercontent.com/20728145/82619259-51e55e80-9b8a-11ea-9331-e78673adb62b.png)

**Comment by michelleogburn** [comment]
3.5 tlsa_Enrollment - [Exit1Age/Exit2Age] issues in spec and sample code

Issue #1: missing parentheses in Sample Code (Exit1Age and Exit2Age)
Without parentheses, `or .. or .. and .. or` is an illogical set of conditions.
![image-20200521-102732](https://user-images.githubusercontent.com/20728145/82619413-c5876b80-9b8a-11ea-8a2e-876b2e55c735.png)

Issue #2: "EntryDate > CohortEnd" issue in both Spec and Sample Code
It seems there is an issue in `or EntryDate > CohortEnd`. Shouldn't it be `or ExitDate > CohortEnd`?
![image-20200521-104907](https://user-images.githubusercontent.com/20728145/82619542-113a1500-9b8b-11ea-9142-aebe5a02ebb0.png)

**Comment by bayboos** [comment]
The "EntryDate > CohortEnd" is more likely incorrect than redundant. The description just above this table says "(Exit1Age/Exit2Age) will differ from EntryAge only when the enrollment **meets the time criteria** for inclusion in the cohort (**ExitDate is between CohortStart and CohortEnd**)...". 

It's a bit difficult to notice because the described logic is the opposite from the one listed in the table. It seems like the first row in the table is supposed to represent the following logic "**equals** EntryAge when the enrollment **does NOT meet** the criteria". 

If it's true, then it should look like this: "ExitDate < CohortStart or **ExitDate** > CohortEnd".

However, that does not explain why the sample code is using very different conditions:

```
when n.ExitDate < cd.CohortStart
				or n.EntryDate > cd.CohortEnd
				or n.EntryDate between cd.CohortStart and cd.CohortEnd 
					and n.ExitDate between cd.CohortStart and cd.CohortEnd
				or n.EntryAge in (98,99) then n.EntryAge
```

The first two lines in the code seem to follow the first line in the specs (which in turn seems to be incorrect); the 5'th line in the code matches the 3'rd line in the specs. But the lines 3 and 4 in the code don't have a direct match in the specs. And are at least partially redundant (yes, this is the place) since a part of the condition "n.**EntryDate** between cd.CohortStart and cd.**CohortEnd**" is already "enforced" by the inner join condition "**n.EntryDate <= cd.CohortEnd **".

I do agree that having no parentheses in this statement makes it a bit difficult to read. And also probably incorrect.

**Comment by michelleogburn** [comment]
@MollyMcEvilley , let me know if you preferred I separate these out into separate issues.

**Comment by MollyMcEvilley** [comment]
3.5.1 - tlsa_Enrollment includes enrollments with exit dates prior to ReportStart, so that isn't an impossible condition.  ActiveAge is the client's age as it is relevant to reporting on the active cohort... Inactive enrollments are relevant to determining household type for system path.  

3.5.2 and 3.5.3 - added missing parentheses!

Re:  EntryDate > CohortEnd for Exit1Age and Exit2Age -- this is calculating age as it is relevant to reporting on Cohort -1 and Cohort -2.  'Future' enrollments are relevant to determining household type for potential returns...
