### ISSUE TITLE
5.4. LSAPerson Demographics - issues in sample code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#202]
1.
![image-20200526-121545](https://user-images.githubusercontent.com/20728145/82965845-35786600-9f7e-11ea-8fd6-3c5c837b386c.png)

The spec provides possible values for `ActiveAge`. 18 is not one of them.

2.
Spec:
Instructions to calculate `DVStatus` for `tlsa_Person` include `CurrentlyFleeing`

![image-20200526-130631](https://user-images.githubusercontent.com/20728145/82965945-7e301f00-9f7e-11ea-90e1-48b6acc3a97d.png)

But this was already calculated in DVStatus in step 3.4.

![image-20200526-133752](https://user-images.githubusercontent.com/20728145/82965997-9dc74780-9f7e-11ea-8e40-01be58e80a57.png)

Why not re-use it? The sample code looks correct. But spec is different.

**Comment by MollyMcEvilley** [comment]
As we discussed on the office hours call on 5/28:  

- People who are 18, 19, 20, or 21 will have an **ActiveAge** value of 21.  
- **ActiveAge** values for all other adults of known age are between 24 and 65.
- The result of selecting records where 'ActiveAge between 18 and 65' and where 'ActiveAge between 21 and 65' will produce identical results -- all of the **ActiveAge** values for adults are between 18 and 65 and also betwen 21 and 65.  
- The code uses the broader category -- 'between 18 and 65' -- because it is easier to understand when reading..
