### ISSUE TITLE
Sample LSA export from 5/28 issue: HHParent column in the lsa_Exit.csv file

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/LSASampleCode#206]
We've found a potential issue with the HHParent column in the lsa_Exit.csv file. Our code returns rows with both 0 and 1 in this column, while the sample result have only 0 in all rows. Since the logic behind this field is pretty simple (any household member have relationship to HoH = 2) and there are plenty of those in the sample source, it seems likely that the sample result is incorrect.

**Comment by dburgstrom** [comment]
Hi Michelle. Thanks for flagging this. I've looked into the code section 7.4, first update statement, and the update statement is potentially running many times for each household ID, if there are multiple household members.

In this small screen shot, I am showing the results of the statement in question with the "update" command replaced with "select" and the "variable = " removed to show all the rows that are being queried and the results of each line. There are multiple lines for a single household ID here.

![image](https://user-images.githubusercontent.com/64597095/83557709-1890e500-a4e0-11ea-89a2-9a545652d6a9.png)

There is no aggregate function to look for the max of "case when parent.PersonalID is not null then 1 else 0 end". We suspect that SQL is updating in a different order on our machine versus yours, and updating every household ID with the head of household's response of 0, because no head of household has a relationship of "child" with her- or himself.

I will recommend that the code be updated.

**Comment by MollyMcEvilley** [comment]
Corrected the way HHVet, HHDisability, HHFleeingDV, and HHParent are set in 7.4.1 to address this issue.

**Comment by dburgstrom** [comment]
Re-ran with the updated code and now see 203 households with "1" marked for HHParent.

**Comment by MichelleNevius** [comment]
Hi David, I don't know for sure this will get to you on a closed item, but could you check your data output, please? (Ticket was marked closed by Molly, not by me, after a new set was distributed with 2020_06_04 in the name, but I don't see those households with 1 for HHParent.)

**Comment by dburgstrom** [comment]
I do still get e-mail notifications for closed issues, it appears. I downloaded the 2020_06_04 file and opened LSAHousehold.csv with Excel and see the following:
![image](https://user-images.githubusercontent.com/64597095/84180877-39b08300-aa56-11ea-958a-3760bd50d02d.png)

**Comment by dburgstrom** [comment]
You are correct, I was looking at the wrong file, excuse me. Let me check the sample code and output again. This is still an issue in our output. It should have fixed it but obviously did not, so I will have to do some digging...

**Comment by dburgstrom** [comment]
I believe I have identified the issue. I don't think the previous fix worked and I failed to notice. I have a suggested fix and I will let Molly take it from here.
