### ISSUE TITLE
5.9. ch_Episodes - question about "seven or more contiguous days"

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#215]
In the spec, episodes for LSA must be continuous - i.e., uninterrupted by any period of **seven or more contiguous days**

![image-20200603-091147](https://user-images.githubusercontent.com/20728145/83657197-6146ad80-a575-11ea-8e46-9f62d1ba87f6.png)

But there is no 7+ contiguous days validation neither in "each record..." instructions in the spec nor in the sample code.

Thus, `ch_Episodes` may have 1-day episodes. In this case, it is not clear why spec refers to seven or more contiguous days.

**Comment by MollyMcEvilley** [comment]
In 5.8, any date that falls between 2 ESSHStreetDates that are less than 7 days apart is inserted to ch_Include. 

So if a person has, for example, ES BedNightDates on 5/1/2019 and 5/4/2019, we create records in ch_Include for those nights -- and then also for 5/2 and 5/3. This is 1 episode of 4 days.

If a person has ES BedNightDates on 5/1 and 5/9, we would not create records for the dates between 5/2 and 5/8 because the gap is not less than seven days -- i.e., there is an interruption of seven or more contiguous days in the series of dates.  That would be 2 episodes of 1 day each.
