### ISSUE TITLE
5.10.2 and 5.10.4 - Issue in Sample Code

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#223]
**Spec**
![image-20200605-125026](https://user-images.githubusercontent.com/20728145/84116539-e05c3b80-a9e4-11ea-86eb-f91de6e3f9f2.png)

**Sample Code**
![image-20200605-125045](https://user-images.githubusercontent.com/20728145/84116569-f0741b00-a9e4-11ea-9534-36b9fc56a606.png)

![image-20200605-125308](https://user-images.githubusercontent.com/20728145/84116592-fff36400-a9e4-11ea-96bc-b22ff3990041.png)

**Issue in Sample Code**
For 5.10.2 and 5.10.4, must be `>=` instead of `>`

**Comment by MollyMcEvilley** [comment]
Hi Michelle.  It looks to me like the specs and the code are in agreement -- am I missing something?

Is it the ">=" in the screenshot from the specs?  To clarify, the change in the screenshot from the specs was to _delete_ the equal sign and not to add it -- you can't see the strikethrough because it looks like part of the equal sign:  
> **EntryDate** for ch_Enrollment >= **LastActive**… 
was changed to:
> **EntryDate** for ch_Enrollment > **LastActive**…

**Comment by MollyMcEvilley** [comment]
(The reference to ch_Enrollment in the specs is obsolete -- it should be a reference to records in tlsa_Enrollment where CH = 1.)

**Comment by michelleogburn** [comment]
Ah good. That confused. All fixed now.
