### ISSUE TITLE
4.38 Setting SystemPath for LSAHousehold Does not match Table

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#23]
https://github.com/MollyMcEvilley/LSASampleCode/blob/b73a71cf526231a029240074e09dce3f1b2bb4cf/LSASampleCode.sql#L2493-L2522

![image](https://user-images.githubusercontent.com/44095973/47308005-a9f26280-d5ed-11e8-94e5-7aafa6cc85c8.png)

For some of the values of SystemPath does not match the way it is written in the specs specifically

- SystemPath =4; should check on ESTStatus not ESDays, There should be no check for THDays
- SystemPath =8; should check on ESTStatus not ESDays, There should be no check for THDays
- SystemPath = 11;should check on ESTStatus not ESDays, There should be no check for THDays

**Comment by tcalder** [comment]
Also Note that in the code there are several places where instead of `xStatus = 0`, it is `xStatus <= 0` which could result in a different value and is not detailed that way in the specs

**Comment by MollyMcEvilley** [comment]
For any record where 'ESDays <= 0 and THDays <= 0' (as in the sample code), ESTStatus should always be equal to 0.

We apologize for the confusion; although the end result is the same, we will update the sample code to use ESTStatus = 0 rather than the combination of ESDays and THDays for SystemPaths 4, 8, and 11.
