### ISSUE TITLE
5.10  - needs corrections

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#252]
**Issue 1 - in the spec**
![image-20200619-103609](https://user-images.githubusercontent.com/20728145/85574492-af3a5880-b5eb-11ea-8c7d-54e46ce9cacd.png)

Some closing parentheses are missing.

**Issue 2 - duplicate conditions in spec**
![image-20200619-103731](https://user-images.githubusercontent.com/20728145/85574686-d7c25280-b5eb-11ea-821e-edb32fe9ea70.png)

**Issue 3 - discrepancy between sample code and spec**
![image-20200619-104837](https://user-images.githubusercontent.com/20728145/85574869-f9bbd500-b5eb-11ea-8117-37ba18235330.png)

These issues are causing some problems and need to be addressed.

**Comment by MollyMcEvilley** [comment]
The order/grouping of things differs a little between the specs and the code, but (unless i'm missing something) they say the same thing.  (The three bullet points that are repeated 3x in the specs to make them a little more readable occur only once in the code because it's not necessary to repeat them.)
