### ISSUE TITLE
6.12 question about hmis_Services usage

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#262]
Sample code (**step 3.3.1**) has the following restrictions for bed-nights:

- `DateProvided between '10/1/2012' and ReportEnd`
- `DateProvided >= nbn.EntryDate`
- `DateProvided < nbnx.ExitDate`

![image-20200617-130330](https://user-images.githubusercontent.com/20728145/85764702-63121580-b6ca-11ea-8f5c-c03c77ca1624.png)

Sample code (**step 5.8.2**) has very similar restrictions. But `DateProvided between '10/1/2012' and ReportEnd` **is missing. Is this correct**?

![image-20200617-130809](https://user-images.githubusercontent.com/20728145/85765155-b4baa000-b6ca-11ea-913a-8082c45701b0.png)

**Step 6.12.2.b** has only `DateProvided <=ReportEnd`.
![image-20200617-130953](https://user-images.githubusercontent.com/20728145/85765323-db78d680-b6ca-11ea-8941-271ae7cabe25.png)

It is very confusing to have different logic in similar sections to select bed-nights.

Please confirm bed-nights for 5.8.2 and 6.12.2.b.

**Comment by MollyMcEvilley** [comment]
In 3.3.1, we need to verify that any nbn enrollment being included was active -- i.e., has at least one bed night -- on or after 10/1/2012.  That doesn't mean that bednights prior to 10/1/2012 are irrelevant for all purposes.

In 5.8.2, the date range is already limited to each client's most recent 3 years of activity, so 10/1/2012 is irrelevant.

I added a note to the specs section 6.12 to clarify that a BednightDate must be valid (i.e., fall between EntryDate and ExitDate if there is one) in order to be relevant and added code to 6.12.2.b to exclude:

1. Invalid data (dates that fall outside of the enrollment date range).  This won't make any change to output except in systems that allow the creation of invalid bed night data.
2. Dates prior to 10/1/2012.  This won't make any change to the output -- they would be ignored in the next step anyway -- but it's potentially a performance improvement.
