### ISSUE TITLE
8.6 and 8.7 - question about [Population and HHType] section

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#287]
Please explain how to use "Population and HHType" section for the selections?

i.e. section 8.6 and section 8.7 have such a different "Population and HHType" list.

But both section 8.6 and 8.7 are developed in the same query in the sample code.

In the same way, our developer is not sure how `ref_Populations` should be used.

![image-20200629-100615](https://user-images.githubusercontent.com/20728145/86552611-5c22a880-befd-11ea-99fa-ab0c599a1507.png)

### Section 8.6
![image-20200629-100331](https://user-images.githubusercontent.com/20728145/86552675-8d9b7400-befd-11ea-9653-08292672670d.png)

### Section 8.7
![image-20200629-100434](https://user-images.githubusercontent.com/20728145/86552697-9b50f980-befd-11ea-824a-a5ff52fa3d95.png)

**Comment by MollyMcEvilley** [comment]
- The Population column is used to identify which populations the report row is required for.
- The HHType column is used to identify the subset of the population by HHType that the report row is required for. As noted in Section 8.1, zero (0) represents a count of all records that meet the criteria, regardless of household type.
-  Section 8.6 and 8.7 have different population lists because they are what the AHAR team requested.  
- The criteria column identifies the criteria in LSAExit for identifying the population.
- ref_Populations lists each population and includes column values that correspond to the criteria.  By joining to it and specifying which populations are relevant, it is possible to use a single statement to generate the report rows for all required populations rather than writing separate statements for each.
