### ISSUE TITLE
9.2 Cohort 1 (Status1) Possible Issues in Where Statements

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#319]
After working through the code and attempting to get numbers to match up with the sample export, we are finding that the cohort 1 numbers do not match and there is some confusion on the use of the following:
(n.RelationshipToHoH = 1 AND n.Status1 IS NOT NULL)
There multiple uses of this (LengthOfStay1, HomelessDate1, etc...) and it seems to be bringing back the wrong amount of people/enrollments.

Example:  Length of Stay is returning 11 enrollments 6 of which have a Status1 of a 1 or a 0 which matches the sample output.  5 of them have a Status1 of 99.  We are wondering if the Status1 statement should look something like:
(n.RelationshipToHoH = 1 AND n.Status1 = 0) 
By including 99s for that DQ measure, we are including folks who cannot be determined if they are an adult and should be included.  Is this what was intended?

**Comment by MollyMcEvilley** [comment]
Using **LengthOfStay1** as an example:

- _LengthOfStay_ is required for all heads of household and adults.
- If **Status1** = 0, the client's enrollment age is under 18, so _LengthOfStay_ DQ issues are only counted if _RelationshipToHoH_ = 1
- If **Status1** = 1, the client is an adult and we count any existing DQ issue regardless of _RelationshipToHoH_ 
- If **Status1** = 99, the client's enrollment age is unknown -- but yes, we count a DQ issue for _LengthOfStay_ if _RelationshipToHoH_ = 1 because the field is required for all heads of household regardless of age.
