### ISSUE TITLE
9.1 - Status1 and Status3 description in the Spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#320]
@MollyMcEvilley I hope the next tickets are the end of the litany. Fingers crossed.

![image-20200706-134633 (1)](https://user-images.githubusercontent.com/20728145/87119166-108c3980-c232-11ea-9b82-199c4fcb2e16.png)

1. space between `(AgeDate)` and `where` for Status1
2. dot after `Cohort = 20` for Status3

**Comment by MollyMcEvilley** [comment]
Thank you!  These typos have been corrected in the next commit of the specs document (the changes aren't tracked because it seems silly to make someone else accept v. straightforward correction of typos).

![image](https://user-images.githubusercontent.com/6156815/89588483-b58a3a00-d811-11ea-9c05-c70024c01a2a.png)
