### ISSUE TITLE
9.2 - RelationshipToHoH1/3 - issue in the Spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#323]
### Sample Code
![image-20200707-110945](https://user-images.githubusercontent.com/20728145/87119744-aecccf00-c233-11ea-8bb0-f2e92a09ac4b.png)

### Spec
![image-20200707-111005](https://user-images.githubusercontent.com/20728145/87119763-bc825480-c233-11ea-92eb-4a72d62d6e78.png)

### Spec Issue
`RelationshipToHoH is null` is missing.

**Comment by bayboos** [comment]
I don't believe anything is missing here. The specs are human-readably clear: any value other than int 1 trough 5 meets the criteria - and that obviously includes "no value at all". The "or is null" part in the code is the SQL "thing" only - for most of the SQL implementations, "null value" is never equal to any other value, but it's also never "not equal" to any other value (in other words: both `1 = null` and `1 <> null` will return false). 

The difference between code and specs does make sense here: the specs are meant to be clear for everybody, including non-programmers. Adding "or empty"/"or not exists" in this case can bring unnecessary confusion (because for "common folks" the "not between .... " phrase already includes it). However we - the programmers - know that we have to add this to the code whenever the null value can be encountered simply because the code is more logical (and more literal) than the spoken language.

**Comment by michelleogburn** [comment]
Closing. @MollyMcEvilley can reopen if she disagrees.
