### ISSUE TITLE
**9.2 - Destination1/3 discrepancy **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#330]
![image-20200708-111602](https://user-images.githubusercontent.com/20728145/87120714-f81e1e00-c235-11ea-97ca-bbd1352baa66.png)

### Question:
1. Why does `Destination1` use `x.ExitDate` but `Destination3` uses `n.ExitDate`? I believe their values are the same, just curious.
2. `dq_Enrollment.ExitDate` = `hmis_Exit.ExitDate` where `hmis_Exit.ExitDate BETWEEN cd3.CohortStart and cd3.CohortEnd`. Thus, `ExitDate` = `cd3.CohortStart` and `ExitDate` = `cd3.CohortEnd` are possible.
a. **why for** `Destination1` **there is a restriction** `ExitDate > rpt.ReportStart` **but for** `Destination3` **it is OK to have** `ExitDate`= `cd3.CohortStart`**?** **Maybe** `n.ExitDate is not null` **should be replaced with** `n.ExitDate > cd3.CohortStart` but in this case we should join `cd3`.

![image-20200708-113843](https://user-images.githubusercontent.com/20728145/87121014-b93c9800-c236-11ea-9cc7-e8a7463a30b5.png)

3. I wonder why only `Destination1/3` have `ExitDate > CohortStart` restriction?  Enrollments with `ExitDate = cd1/3.CohortStart` are successfully used in `ClientExit1/3` and `HoHPermToPH1/3` . Please advise.

**Comment by MollyMcEvilley** [comment]
The only potential difference between x.ExitDate and n.ExitDate is that n.ExitDate is only non-NULL if the exit occurred <= ReportEnd.  By using n.ExitDate (in conjunction with **Status1** for **Destination1** and by itself for **Destination3**), we can eliminate the comparison of the exit date to the cohort periods.  

I have updated the code to do that so that they are consistent with one another and with the use of Status1 for other DQ columns.
