### ISSUE TITLE
**Section 9 - DateDeleted restriction is missing in Sample Code**

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#340]
@MollyMcEvilley , can you provide us `hmis_*` tables structure?

1. It would be very helpful for developer to import test data on our MSSQL server
2. it will help a lot to find missing DateDeleted restrictions in Sample Code

**Section 9.1** - `DateDeleted IS NULL` is missing for:

- `hmis_Enrollment` (nested query)
- `hmis_Project `main query
- `hmis_Project` nested query
![image-20200708-132511](https://user-images.githubusercontent.com/20728145/87548626-9dcff380-c661-11ea-9b9f-0aa4e5182d6c.png)

**Section 9.2**: `NoCoC` 
`DateDeleted IS NULL` is missing for:

- `hmis_Project`
- `hmis_Enrollment `

but `hmis_EnrollmentCoC` has  `coc.DateDeleted is null` twice.
![image-20200708-133221](https://user-images.githubusercontent.com/20728145/87548878-f7d0b900-c661-11ea-9b60-e68ba04bddd0.png)

**Section 9.2**: `NotOneHoH1`
`DateDeleted IS NULL` is missing for:

- `hmis_Enrollment`
![image-20200708-133657](https://user-images.githubusercontent.com/20728145/87549100-3c5c5480-c662-11ea-9908-2bb196cb7fa2.png)

**Section 9.2**: `NotOneHoH3`
`DateDeleted IS NULL` is missing for:

- `hmis_Enrollment `
![image-20200708-133732](https://user-images.githubusercontent.com/20728145/87549224-6746a880-c662-11ea-99ad-e2d188fa8589.png)

**Comment by MollyMcEvilley** [comment]
Adding restriction for hmis_Enrollment in 9.1 and 9.2 (**NoCoC**, **NotOneHoH1**, and **NotOneHoH3**)

Commit forthcoming

It is not needed for hmis_Project because it is not possible for an enrollment to exist in an undeleted state if its associated _ProjectID_ does not exist in an undeleted state.  (This is conceptually related to the fact that there is no join to hmis_Client in the selection of HHID and Enrollment records in 3.3 and 3.4 or any need to specify `WHERE hmis_Client._DateDeleted_ is NULL` in the selection of LSAPerson records in 5.3.)
