### ISSUE TITLE
*9.2 - NoCoC and NotOneHoH1/3 - hmis_Project questions*

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#347]
### Question 1
There is `ProjectType in (1,2,3,8,13)` restriction for `NoCoC`  (both sample code and spec)

That is about `ProjectType = [9, 10]` that are part of Systemwide LSA report? Were `ProjectType = [9, 10]` intentionally excluded from `NoCoC` calculation?

`NotOneHoH1/3` also has `ProjectType` restriction in the Spec. But in sample code only `dq_Enrollment` is used. But `dq_Enrollment` must be based on `ProjectID in lsa_Project` so `ProjectType` is different(!). Please advise.

### Question 2
To select households for LSA report we also use a restriction by OperatingEndDate (step 3.3.1). I wonder if the restriction by OperatingEndDate was intentionally excluded from `NoCoC` calculation?
![image-20200713-100617](https://user-images.githubusercontent.com/20728145/87551453-403da600-c665-11ea-8f4f-4e341ef1b854.png)

![image-20200713-101853](https://user-images.githubusercontent.com/20728145/87551496-4df32b80-c665-11ea-8799-9eab41d44c8b.png)

**Comment by MollyMcEvilley** [comment]
### Question 1
Yikes.  Project types 9 and 10 should be excluded from every part of the LSA except the PDDE files... I added the project type restriction in 9.1.
### Question 2
Yes, the _OperatingEndDate_ criteria was intentionally excluded.  We are looking for DQ issues, so we don't want to exclude an enrollment from dq_Enrollment BECAUSE of a DQ issue.
