### ISSUE TITLE
*** 8.14: PopID = [113 .. 128] issues ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#393]
### Spec
![image-20200803-145627](https://user-images.githubusercontent.com/20728145/89262560-9d81a300-d5e4-11ea-8bcd-d0115f074835.png)

### Sample Code
![image-20200803-145900](https://user-images.githubusercontent.com/20728145/89262603-ac685580-d5e4-11ea-95d4-59b4b2077a2a.png)

![image-20200803-145736](https://user-images.githubusercontent.com/20728145/89262631-b5f1bd80-d5e4-11ea-8349-bd72924f8efd.png)

### Issue

1. Spec refers to `tlsa_Enrollment.ActiveAge`; in Sample code `tlsa_Enrollment.ActiveAge` is compared with `pop.Age`; Population table uses `HHAdultAge` that is compared with `tlsa_HHID.HHAdultAge` in sample code. Which age column should be used and which must be removed to avoid confusion?
2. Spec uses `tlsa_Enrollment.ActiveAge` = 21, but in Population table `HHAdultAge` = 18. We again mess age = 18 and age = 21
3. Spec uses `tlsa_Enrollment.RelationshipToHoH = 1` restriction that is missing is sample code.

**NOTE: the issues should be fixed in PopID = [113 .. 128]**

**Comment by MollyMcEvilley** [comment]
This is a big one.  Three changes:
1.  Update specs to clarify that counts of parenting children/youth are limited to HoH.
2.  Update ref_Populations records for parenting youth (popIDs 113 to 128) to use Age and not HHAdultAge.*
3.  Update sample code to split counts for parenting children/youth (113 to 144) into separate steps from counts for other populations that include all household members.  Joining tlsa_HHID and tlsa_Enrollment on **EnrollmentID** rather than **HouseholdID** limits these counts to HoH.

*If the HoH is, for example, 18 years old and a parent, they are counted in these populations regardless of HHAdultAge / even if there are people > 24 in the household.

Commits forthcoming.
