### ISSUE TITLE
** 8.13, 8.14.1, 8.14.2 - issue with "latest" in sample code **

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#399]
### Sample Code
![image-20200803-124851](https://user-images.githubusercontent.com/20728145/89264275-7c6e8180-d5e7-11ea-8562-3916819d070a.png)

Item 2 in graphic was addressed under #301 . Molly replied:

> Those are very weird anomalies -- possibly copy/paste errors. Deleting everything after the last ‘and' on the far left.

However, the ticket is still open and no changes were made to the sample code.

Item 1 in graphic: This part of code also shouldn't be in the sample code.

**Please note, 8.13, 8.14.1 and 8.14.2 should all be fixed. **

**Comment by MollyMcEvilley** [comment]
I see where the copy/paste error in 8.13 came from.... neither block 1 nor block 2 are needed in 8.13 because it doesn't include PopIDs 24-34.

For PopIDs 24-34, which ARE included in 8.14.1 and 8.14.2, the criteria for inclusion is based on the maximum ActiveAge.  We need block 1 to get the maximum ActiveAge.  We need block 2 to specify whether  it matters or not.  I am removing the code in block 2 that doesn't count it as relevant for the point-in-time cohorts (`cd.Cohort <>1`).  Theoretically, there will only be one active enrollment on a point-in-time date, but the specs don't exclude those cohorts and it removes the possibility of overlapping enrollments with different age groups causing some people to be double-counted.
