### ISSUE TITLE
*** 8.13 - "Population" issues ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#400]
### Spec
![image-20200803-115842](https://user-images.githubusercontent.com/20728145/89264650-23ebb400-d5e8-11ea-841f-89fe77caf6df.png)

### Sample Code
![image-20200803-121708](https://user-images.githubusercontent.com/20728145/89264695-349c2a00-d5e8-11ea-9cfb-0265451df6b2.png)

`where  (pop.PopID in (3,6) or pop.popID between 145 and 148)
		and pop.PopType = 3
		and pop.ProjectLevelCount = 1`

### Sample Code - exact rows from "ref_Populations" table
![image-20200803-120203](https://user-images.githubusercontent.com/20728145/89264784-5e555100-d5e8-11ea-943b-d94ef434629c.png)

### Issues

- “`Age`” field is not listed in “Criteria” column for rows 145, 145, 147, 148 in the spec;
- sample code uses `hhid.HHAdultAge = pop.HHAdultAge` but `HHAdultAge` is not used in the spec;
- according to the spec, PopID = 145 describes only one scenario, but the sample code returns two scenarios;
- according to the spec, PopID = 147 describes only one scenario, but the sample code returns two scenarios;
- What `ref_Populations` field should be compatible with `tlsa_Enrollment.ActiveAge`? It looks like there is an issue in the spec. Spec uses `n.ActiveAge = pop.Age` but it causes issues for `tlsa_Enrollment.ActiveAge` = 18 because for rows 145 and 147 `pop.Age`= 21 and not 18.
- I believe Molly used `ProjectLevelCount = 1` to limit rows from `ref_Populations` table similar as `Core = 1` was used. Is it correct? If yes, not sure why `(pop.PopID in (3,6) or pop.popID between 145 and 148)` and `pop.PopType = 3` are used.

**Comment by MollyMcEvilley** [comment]
![image](https://user-images.githubusercontent.com/6156815/90153439-fe347c80-dd56-11ea-93ae-56001df60404.png)

The specs edits shown above in the commit referenced above should address all but the last bullet... 

The `Core = 1` (another example is `ReturnSummary = 1`) thingie is a shortcut for groupings that are used over and over.  For this little oddball grouping of popIDs, it didn't make sense (to me, anyway) to create a column to identify them in the table rather than just listing them in the code.

**Comment by MollyMcEvilley** [comment]
Further correction to edits shown above for popIDs 146 and 148 -- not possible to have a person over 21 in a household where HHAdultAge = 18.  Commit forthcoming.
![image](https://user-images.githubusercontent.com/6156815/90620178-1b969a00-e1e0-11ea-9c5c-5a81a0cf73d0.png)
