### ISSUE TITLE
Step 4.40 Get (HHType for) Exit Cohort Members and Enrollments

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#43]
(AAQ 129151) We have a question regarding LSA 4.40 while setting HHType for the person within one household. In the sample code it mentioned that ‘inner join tmp_CohortDates cd on cd.CohortEnd >= hn.EntryDate’, then one application will be counted towards multiple Cohort, simple scenario, one household with only one member in this case, will be counted multiple times, then the HHType been calculated based on this is problematic. You may use EnrollmentID=767524 and with PersonID=345758. According to the sample code, this person will be counted multiple times in section 4.40. Please clarify on this issue. A screenshot is attached for your review.
 
<img width="342" alt="lsa4 40" src="https://user-images.githubusercontent.com/44678553/47865879-c5baed00-ddd3-11e8-8851-a95100f999ee.PNG">

**Comment by MollyMcEvilley** [comment]
If I am understanding the question correctly, the code here is correct.

There is an inner join on HouseholdID from the outer/main query -- where cohort is set -- to the subquery where this code occurs.  

- Because HHType for prior activity is based solely on HH member ages AT PROJECT ENTRY, it wouldn't be appropriate to restrict exit dates any further in the subquery.  
- Based on the criteria in the outer query, it's only possible for an EnrollmentID to be associated with one cohort (ExitDate must be between CohortStart and CohortEnd and Cohort must be <= 0).

**Comment by MollyMcEvilley** [comment]
I was not understanding the question correctly -- this is the source of the problem in issue #55.
