### ISSUE TITLE
* 8.17, 8.18 - sample code uses "Active = 1" that is not in the spec *

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#431]
## Sample Code
![image](https://user-images.githubusercontent.com/6241517/89451879-7c26d100-d722-11ea-8299-350da58afc0a.png)

## Spec
There are no instructions to use Active = 1 in sections 8.17 and 8.18: 
![image](https://user-images.githubusercontent.com/6241517/89451913-83e67580-d722-11ea-9bab-8213673d1e66.png)

I believe it's an issue in the specs and sections 8.17 and 8.18 should be updated similar to section 8.16:
![image](https://user-images.githubusercontent.com/6241517/89451941-8ba61a00-d722-11ea-8c40-add14087acff.png)

**Comment by MollyMcEvilley** [comment]
In all (or nearly all) of the 8.x counts where the specs note that **Active** should = 1, it turns out to be extraneous in the code because criteria in the joins for entry/exit/bednight dates as they relate to report/cohort start and end dates are consistent with but more specific than the criteria used to set **Active** = 1 in section 5.2.*

I removed it from the sample code WHERE clause in 8.17 and 8.18 because it's superfluous, but for now I'm going to leave other sections alone.

*I am very lightly editing section 5.2 of the specs because it defined the logic for identification of active enrollments, but did not explicitly state that the end result should be that they are flagged with **Active** = 1 in tlsa_Enrollment.  

Commits forthcoming.
