### ISSUE TITLE
*** 5.8.3 - last changes caused new issues ***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#438]
After last changes under https://github.com/HMIS/LSASampleCode/issues/299 - new issues appeared:

## Spec
![image](https://user-images.githubusercontent.com/6241517/89453633-2dc70180-d725-11ea-865d-38fea2a99e7c.png)

## Sample Code
![image](https://user-images.githubusercontent.com/6241517/89453643-328bb580-d725-11ea-87d2-e7fd998d3778.png)

## Isues
- block # 1: is true even just for `chn.ProjectType in (1,8)`  but it is not written in the spec;
- block # 2: according to the spec, it must be true only for `ProjectType in (1,8,2)` but there is no such restriction in sample code;
- block # 3: spec has specific rules for `ProjectType in (13,3)` but they are missing in the sample code.

**Comment by MollyMcEvilley** [comment]
I have re-written/re-grouped the criteria in the specs and re-written the code so that it more closely reflects the way the specs are written. (Commits forthcoming)

block # 1 issue - LivingSituation should be in (1,18,16) if ProjectType in (1,8) -- the project type alone is not enough -- corrected this in code step 5.8.3
block # 2 issue - dates on or after EntryDate for ProjectType (3,13) were previously inserted in 5.8.4 -- re-wrote code in 5.8.3 so that all dates are inserted there (deleted 5.8.4)
block # 3 issue - (same resolution as block # 2)

**Comment by Ladvien** [comment]
Thank you, @MollyMcEvilley.  Only been in the mix a couple days, but really appreciate your quick responses!
