### ISSUE TITLE
Step 4.69 DQ for TimesHomeless and MonthsHomeless

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#45]
(AAQ 129523) In step 4.69 where it calculates DQ for TimesHomeless1/MonthsHomeless1 and in step 4.71 for DQ for TimesHomeless3/MonthsHomeless3 there seems to be an issue and I believe we need to add a line to the 'where' clause.

(hn.ProjectType in (1,2,8) or (hn.ProjectType in (3,13) and hn.PreviousStreetESSH = 1))

If we have ProjectType in 1,2,8 the 3 Questions (Homeless Start Date, Times Homeless in 3 Years, Total Months Homeless in 3 Years) will automatically be available for all HOH and Adults and Elelment 3.917A
BUT
If we have ProjectType in 3,13 the 3 Questions (Homeless Start Date, Times Homeless in 3 Years, Total Months Homeless in 3 Years) will ONLY be available for all HOH and Adults and Elelment 3.917B IF the dependency fields led the user to answer the Question"On Night before did client stay on the Streets, ES or SH?"=Yes.  So it could potentially be null and should not be picked up as a DQ issue. 
It looks like the Homeless Start Date is calculating ok, but for Times Homeless and Months Homeless I think the where clauses should look something like below:
where (an.RelationshipToHoH = 1 or an.AgeGroup between 18 and 65)
and (
(hn.ProjectType in (1,2,8) or (hn.ProjectType in (3,13) and hn.PreviousStreetESSH = 1))
and (hn.TimesHomelessPastThreeYears not between 1 and 4 or hn.TimesHomelessPastThreeYears is null)
)

**Comment by TanyaPieterse** [comment]
The filter part should be:
(hn.ProjectType in (1,8) or (hn.ProjectType in (2,3,13) and hn.PreviousStreetESSH = 1))
I had it incorrect above :)

**Comment by MollyMcEvilley** [comment]
TimesHomeless and MonthsHomeless aren't dependent fields per the HMIS Data Dictionary for 3.917A or 3.917B.  

For some project types (HP), the Dictionary requirement doesn't actually make any sense -- 0 isn't an option for TimesHomeless and it's very possible that a prevention client was never homeless -- but every one of the LSA project types either requires that clients are homeless at entry for eligibility OR establishes them as homeless based on the fact of their project entry (e.g., ES).  So -- regardless of project type or PreviousStreetESSH, TimesHomeless and MonthsHomeless are required...

**Comment by MollyMcEvilley** [comment]
[Post-ice storm delay] Corrections to the sample code have been made so that circumstances under which _DateToStreetESSH_, _TimesHomelessPastThreeYears_, and _MonthsHomelessPastThreeYears_ are required are properly identified.  

It is important to note that these changes are NOT CONSISTENT with the specs because the specs are wrong.  (The error is due to a years-long gap in my awareness that the fields numbered 3, 4, and 5 are standard in 3.917A and dependent in 3.917B -- see erroneous comment from November 8.)  Given the date, the specs will not be updated; DQ for these fields will be ignored for FY18.
