### ISSUE TITLE
Clarifying question for 4.5

### ISSUE THREAD

**Issue by amusillamiSSG** [abtassociates/LSASampleCode#469]
For 4.5 Get Inventory.csv Records / lsa_Inventory. There is filtering criteria in the table highlighted below. However, that filtering criteria isn’t present in the logic below the table and according to my dev team it also doesn’t exist in the sample SQL. Should we be trusting the filters that are highlighted in the table?

![image](https://user-images.githubusercontent.com/66274207/90550396-83ec6980-e155-11ea-81e3-0d1a1bb22e7a.png)

**Comment by MollyMcEvilley** [comment]
Only the columns specified in the Logic section should be used to filter data.

The Column Descriptions identify differences between general HMIS CSV requirements for the file and those specific to the LSA. For example, _ProjectType_ may be NULL in HMIS if _ContinuumProject_ = 0, but may not be NULL in the LSA at all ever because all projects included in the upload must have _ContinuumProject_ = 1.
