### ISSUE TITLE
4.28.d Top 1 EnrollmentID

### ISSUE THREAD

**Issue by JulesABrown** [abtassociates/LSASampleCode#47]
(AAQ 129419) In the where clauses where it checks for top 1 EnrollmentID in active_Enrollment, I believe we need to add 'and ExitDate is not null' so that we can pull the last EXITED EnrollmentID from the file?

**Comment by TanyaPieterse** [comment]
This is for the where clauses in Step 4.28.d.  
Example:
where lhh.RRHDestination is null 
	and hn.EnrollmentID in 
		(select top 1 an.EnrollmentID 
		 from active_Enrollment an
		 where an.ProjectType = 13
			and an.PersonalID = lhh.HoHID
			and an.RelationshipToHoH = 1
			and an.HHType = lhh.HHType
                        **and an.ExitDate is not null**
		 order by an.ExitDate desc)

**Comment by MollyMcEvilley** [comment]
This isn't necessary because, if there is any open enrollment that meets the criteria for project and household type, the destination will be set to -1 in the statement immediately prior to this UPDATE query.  (There shouldn't BE a destination set for any household with an active enrollment in the project type at the end of the report period.)
