### ISSUE TITLE
*** Request - hmis_* table structure ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#484]
Hi @MollyMcEvilley 

We previously asked for this, but it was included with another issue... 

So, is it possible to get the hmis_* create table structure? This would help us to import the test data into our test code against your sample code.

**Comment by bayboos** [comment]
As far as I know, the hmis_* tables are supposed to conform with HMIS Data Exchange CSV format. This is backed up by the fact that sample data kit provides data in this exact format, and feeding them directly into the code generates expected results (more or less). All the documentation (much more than needed) can be found on this page:

https://www.hudexchange.info/resource/3824/hmis-data-dictionary/

Specifically, the structure of the tables and expected/required set of data is described in this document:

https://hudhdx.info/Resources/Vendors/HMIS%20CSV%20Specifications%20FY2020%20v1.8.pdf

Obviously, the way of creating those tables and populating them with the real-life data depends on how the data are collected/stored by your system; if your system is alread capable of exporting data in the HMIS CSV format it should be easy enough to convert it to output the data as the database tables instead of files.

**Comment by MollyMcEvilley** [comment]
I'm sorry -- this is outside the scope of the sample code.
