### ISSUE TITLE
** 7.6.3 ambiguity in the "lastDay" subquery **

### ISSUE THREAD

**Issue by bayboos** [abtassociates/LSASampleCode#485]
Hello

The 7.6.1 step is updating LastInactive date using the following query:

![inner_join](https://user-images.githubusercontent.com/64633390/91297486-b40fba00-e79e-11ea-9c9a-e7e73374fa69.PNG)

Acc to this query, the LastInactive value is supposed to come from tlsa_HHID table, matching the row by the highlighted condition. For an example HoH with PersonalID = 61947, the tlsa_HHID table have three rows (with different HouseholdID values - as expected):

![hhid](https://user-images.githubusercontent.com/64633390/91298212-e7067d80-e79f-11ea-818f-97a66ef1aefc.PNG)

Everything seems to be ok with the tlsa_HHID table since the one generated by our system does match the one from the Sample Data Kit. HOWEVER despite the match in tlsa_HHID table, the results of the 7.6.1 query is different:

![sample_vs_actual](https://user-images.githubusercontent.com/64633390/91298409-482e5100-e7a0-11ea-86ad-db8550404e95.PNG)

The result generated by our system is on the left, the table provided with the Sample Data Kit is on the right. Our system does find different LastInactive dates, which is expected due to the condition highlighted on the first image; yet both rows in the Sample Data Kit have the same LastInactive date (even though QualifyingExitHHID is different).

There are 33 rows in the tlsa_exit table that are in the same situation. This discrepancy directly impacts the final results because LastInactive date is used to determine SystemPath value, which in many of those 33 cases (but not all) is also different.

Please explain or correct; any response will be highly appreciated.

**Comment by dburgstrom** [comment]
Working through this, I see the same 3 rows exactly as shown in your first image, after running up to but not including step 7.6.1. Then, after running step 7.6.1, only QualifyingExitHHID 169416 has its LastInactive value updated to '4/10/2017'. QualifyingExitHHID 169671 is left blank, because it does not meet either of the two conditions in the WHERE clause: its value for Stat is 5 and EnrollmentID 169671 is returned in the subquery.

![image](https://user-images.githubusercontent.com/64597095/91314161-40f94a00-e784-11ea-9c30-954f22f79bb2.png)

Next, when we get to step 7.6.3, the code left joins to a subquery called "lastDay", by HoHID and HHType. But two identical rows are returned for HoHID 61947, each with different inactive dates:

![image](https://user-images.githubusercontent.com/64597095/91314431-8f0e4d80-e784-11ea-8a5e-aaa7ec95e03b.png)

In my instance, the '4/10/2017' date is returned first. The row with NULL LastInactive for HoHID=61947 in tlsa_Exit is then set to '4/10/2017' for the LastInactive date and remains that way for the rest of the sample code (I only verified through step 7.7.4, which is the last step recorded in the tlsa_Exit file for that row).

**Comment by bayboos** [comment]
Thank you very much for your reply. You are absolutely right; looks like there is more disambiguation needed, either in the subquery itself (to return only one row) or in the join conditions (to use specific one rather than picking one at random). Looks like this will require an input from @MollyMcEvilley .

Edited the subject line to better describe the identified issue.

**Comment by MollyMcEvilley** [comment]
Commits forthcoming:
7.2 - added disambiguation criteria to specs and sample code for selection of **QualifyingExitHHID**
     - split into 3 separate steps in the sample code to ensure  
7.5 - added disambiguation criteria to specs and sample code for selection of prior enrollment for system engagement status
7.6.3 - added **Cohort** to the lastDay subquery in both the SELECT and join to tsla_Exit so that **LastInactive** is updated for all records of **HoHID**/**HHType** combinations that occur in multiple cohorts
