### ISSUE TITLE
*** 5.8.3 - possible issue ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#495]
This is a follow-up to #481

From our developer...

You know I am happy when we close tickets, But @MollyMcEvilley wrote: 

> `ProjectType NOT in (1,8)` has to stay.

So if it is a must-be condition, that means that every other places without `ProjectType NOT in (1,8)` for `PreviousStreetESSH = 1` should be fixed (**both sample code and spec**):

- 6.14.1
- 6.14.2
- HomelessDate1
- HomelessDate3
- TimesHomeless1
- TimesHomeless3
- MonthsHomeless1
- MonthsHomeless3
![image-20200828-092915](https://user-images.githubusercontent.com/20728145/91866769-b606cc80-ec27-11ea-8b7b-885f351df26a.png)

**Comment by MollyMcEvilley** [comment]
`ProjectType not in (1,8)` is not required in the highlighted parenthetical clauses above because ES/SH records are already included no matter what -- we don't have to exclude them under any circumstances.  The same is true for all of the listed DQ columns.

It's different in section 5.8.3.  It IS required and upon further review, I should not have made the change (add `ProjectType in (1,8)` to the WHERE clause) that I made in response to issue #481 -- it isn't consistent with the specs -- and I will be updating it shortly.
