### ISSUE TITLE
Performance of LSA sample queries

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#5]
We've done some work to get the LSA sample queries to run against large data sets.  The first set of speed improvements are in Pull Request #4 .  This covers moving some inner queries into temporary tables and indexing them.  

If people think this is helpful, we also optimized the ReportStart and ReportEnd values into variables and I can setup another pull request for those changes.

**Comment by TimLawrencePCL** [comment]
Thanks for the pull request.  For a variety of reasons I don't think we want to introduce these kind of changes to the main branch while people are trying to finish up this initial deployment.  We'll need to decide on a process, but I'm thinking we could maintain a performance improvement branch while the dust settles, then merge it later on.  People will still be able to review the changes in the meantime if they are looking for help with performance.  How does that sound, Molly?

**Comment by eanders** [comment]
That sounds completely reasonable to me. Mostly I wanted to get these out for anyone who's having trouble with performance.  They *shouldn't* affect the results, but I agree, they add some complexity to the code.  It would be great if they could eventually be merged in so that we don't have to maintain multiple long-running branches.

**Comment by MollyMcEvilley** [comment]
I did add a few indexes to the tables that the sample code creates.  We can certainly explore additional performance tuning after the dust settles.  I'm avoiding variables in the sample code so that it's possible to run individual statements in isolation.  

In the interim, in case it's helpful:  
On my system, the indexes with the most impact on execution time are on the hmis_ tables.  I found the code below on [a blog](https://blog.sqlauthority.com/2011/01/03/sql-server-2008-missing-index-script-download/) a few years ago when I was trying to figure out how to get nationwide reporting queries to run in the VA Repository.  It identifies the top 25 'missing' indexes in a database sorted by average estimated impact and generates create statements for them -- and it's amazing. 

-- Missing Index Script
-- Original Author: Pinal Dave 
SELECT TOP 25
dm_mid.database_id AS DatabaseID,
dm_migs.avg_user_impact*(dm_migs.user_seeks+dm_migs.user_scans) Avg_Estimated_Impact,
dm_migs.last_user_seek AS Last_User_Seek,
OBJECT_NAME(dm_mid.OBJECT_ID,dm_mid.database_id) AS [TableName],
'CREATE INDEX [IX_' + OBJECT_NAME(dm_mid.OBJECT_ID,dm_mid.database_id) + '_'
+ REPLACE(REPLACE(REPLACE(ISNULL(dm_mid.equality_columns,''),', ','_'),'[',''),']','') 
+ CASE
WHEN dm_mid.equality_columns IS NOT NULL
AND dm_mid.inequality_columns IS NOT NULL THEN '_'
ELSE ''
END
+ REPLACE(REPLACE(REPLACE(ISNULL(dm_mid.inequality_columns,''),', ','_'),'[',''),']','')
+ ']'
+ ' ON ' + dm_mid.statement
+ ' (' + ISNULL (dm_mid.equality_columns,'')
+ CASE WHEN dm_mid.equality_columns IS NOT NULL AND dm_mid.inequality_columns 
IS NOT NULL THEN ',' ELSE
'' END
+ ISNULL (dm_mid.inequality_columns, '')
+ ')'
+ ISNULL (' INCLUDE (' + dm_mid.included_columns + ')', '') AS Create_Statement
FROM sys.dm_db_missing_index_groups dm_mig
INNER JOIN sys.dm_db_missing_index_group_stats dm_migs
ON dm_migs.group_handle = dm_mig.index_group_handle
INNER JOIN sys.dm_db_missing_index_details dm_mid
ON dm_mig.index_handle = dm_mid.index_handle
WHERE dm_mid.database_ID = DB_ID()
ORDER BY Avg_Estimated_Impact DESC
GO

**Comment by eanders** [comment]
Thanks @MollyMcEvilley I didn't include our hmis_ indexes in the original AAQ since I figured most people would have those.  The PR #4 doesn't include any variable, only temporary tables.  These were the changes that allowed us to run against larger CoCs.

**Comment by eanders** [comment]
Thanks for merging #13!  I'll close this issue as that contains all of our performance improvements.

**Comment by MollyMcEvilley** [comment]
Even on my very small data set, those changes made a big difference -- thanks!  (I had to make a few small changes to get it to run in my db -- mostly just adding GO after the DROP statements for the temp tables.  I hope those changes don't break it for you.
