### ISSUE TITLE
* 8.20 - unexpected "p.OperatingEndDate >= DateProvided " *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#508]
Sample Code uses `and (p.OperatingEndDate is null or p.OperatingEndDate >= DateProvided)` restriction that is not declared in the spec. Shouldn’t this restriction be removed?
![image-20200901-122954](https://user-images.githubusercontent.com/20728145/92081344-c29a3a80-ed77-11ea-8d64-3f4434930eb9.png)

**Comment by MollyMcEvilley** [comment]
I am having trouble reconciling a few conflicting sets of circumstances.  The core problem is with the vague, non-technical nature of the HMIS Data Standards -- there is (almost) no distinction between functional requirements for an HMIS application and data collection instructions for users, entity relationships are not clearly defined, there are no processes defined for things like the creation of an operating end date (e.g., what do you do with open enrollments?  can the system allow the creation of new enrollments and/or services?), and there is no consistent way to validate HMIS data. 
 
1.  Regardless of whether or not this is in the specs, a project that isn't operating can't provide a bed.  If the presence or absence of this line of code would alter the output, the underlying data are bad.
2.  In the past, I have included conditions like this in the code when issues have been submitted that indicate the potential existence of bad data.
3.  In doing so,  I have created an unreasonable expectation that the sample code can and/or should be designed to exclude data that shouldn't exist in the first place.   

This kind of reverse engineering is potentially endless.  I'm not going to change this in the sample code because it shouldn't logically result in any difference in the output -- and if it does, the difference falls in a gray area that has to be acceptable in HUD reporting for as long as the data standards leave so much open to interpretation.
