### ISSUE TITLE
Sample Result Quoting Adjustment Request

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#509]
This is a low priority request, but it would make checking the sample results against test runs much easier if the quoting within the sample results files were consistent.  It appears that integers and dates are not quoted, strings are quoted, and empty cells are sometimes quoted, perhaps based on the underlying column type.

If there's any way to quote everything, or at least consistently quote or not quote empty strings, that would be very helpful. 
Here's an example where some empty cells are quoted others are not:
ProjectCoC.csv
```
"47171020","240","XX-500","391062","123 Anywhere Ave.","","Anytown","XX","12345",2,"2020-04-13 00:00:00","2020-04-13 00:00:00","",,12345
"47171050","808","XX-500","391062","365 Apple Road","","Anytown","XX","12345",2,"2020-04-13 00:00:00","2020-04-13 00:00:00","",,12345
"47171060","957","XX-500","391062","2134 Alpine Pl.","","Anytown","XX","12345",2,"2020-04-13 00:00:00","2020-04-13 00:00:00","",,12345
"47171150","958","XX-500","391062","2134 Alpine Pl.","","Anytown","XX","12345",2,"2020-04-13 00:00:00","2020-04-13 00:00:00","",,12345
```
Similarly in LSACalculated.csv ProjectID appears quoted and empty, so probably quoted because ProjectID is a string.
```
 3,1,-1,3,15,-1,"",1,12345
 3,1,-1,3,16,-1,"",1,12345
 3,1,-1,3,23,-1,"",1,12345
```

If people have a strong aversion to these changes, having written this, I think maybe I understand the logic enough that we might be able to code around it, so maybe just a confirmation of logic for quoting?

**Comment by dburgstrom** [comment]
Half of the key is that our exporter wraps strings in quotes and it does not wrap dates or integers in quotes. The other half of the key is to see what the sample code declares the variable data types to be.

For example, in the HMIS CSV output Funder.csv, the variables FunderID, ProjectID, OtherFunder, GrantID, UserID, and ExportID all are quoted in the sample CSV export dataset from May because they are strings. Funder, StartDate, EndDate, DateCreated, DateUpdated, and DateDeleted are not wrapped in quotes because they are integers or dates.

In the sample code "2_1 to 2_10 Create Output Tables," the table lsa_funder is created and declares all the above dates except for DateDeleted as nvarchar data types of varying length. Our exporter then wraps these dates in quotes because they are strings now and not dates. Hence if you compare the Funder.csv files from the sample data set with the sample LSA results, you will see that dates are wrapped in quotes in one file and not the other.

This is not an exhaustive review of all the files, so if there are exceptions that don't fit this, let me know and I can investigate.

Thanks.
