### ISSUE TITLE
* 7.6.3 - Cohort in lastDay *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#518]
This is a followup to #510 

@MollyMcEvilley responded

> I can't tell which part you're referring to for sure... the changes associated with that issue were in sections 7.2 and 7.5 and the specs were updated in both places.

I will re-phrase what happened before:

Molly fixed 7.6.3 in the sample code:

> 7.6.3 - added **Cohort** to the lastDay subquery in both the SELECT and join to tsla_Exit so that **LastInactive** is updated for all records of **HoHID/HHType** combinations that occur in multiple cohorts

Spec doesn’t have instructions to limit `sys_TimePadded` by `Cohort` when `LastInactive` is calculated. Shouldn’t spec be updated with the added `Cohort` logic?

**Comment by MollyMcEvilley** [comment]
Some of the relevant info -- including the need to group by cohort -- is in the column descriptions for sys_TimePadded.

![image](https://user-images.githubusercontent.com/6156815/94810161-a5ca4480-03c1-11eb-952b-f4435e060af7.png)

Also correcting typos in the logic section -- which referenced **ExitCohort** instead of tlsa_Exit.Cohort -- that may have been contributing to confusion.
 
![image](https://user-images.githubusercontent.com/6156815/94810630-44ef3c00-03c2-11eb-9185-7061b60c5595.png)
