### ISSUE TITLE
8.19: redundant ContinuumProject and EnrollmentCoC restrictions in the spec

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#520]
This is a followup to #411 

@MollyMcEvilley wrote

> It's left over from before tlsa_Enrollment existed...

But the spec wasn’t updated.

**Comment by MollyMcEvilley** [comment]
#411 was closed because the language is redundant but not wrong in any way that will impact output and I can't address it at this point.

(Note:  I did not set the policy on fix/not fix -- it came from HUD.  I'm happy to flag these for fixing if there is funding for that at a later date, but all funding for sample code and specs has long since been expended.)
