### ISSUE TITLE
-1 result for lsa_household.Other3917Days

### ISSUE THREAD

**Issue by TimLawrencePCL** [abtassociates/LSASampleCode#54]
The calculation described in the comment for 4.35 doesn't seem to match the code in the UPDATE.  The code allows lsa_household.Other3917Days = -1 in some circumstances, which isn't legal.  I changed line 2409 to this, which seems right and fixed my problem:

	-- , lhh.LastInactive))
	, dateadd(dd, 1, lhh.LastInactive)))

https://github.com/MollyMcEvilley/LSASampleCode/blob/055d75259508e2acf86926f93b1757f54d28a5b8/LSASampleCode.sql#L2409

**Comment by MollyMcEvilley** [comment]
I think the root of the issue was in the WHERE clause and due to my over-fondness for 'BETWEEN' vs separate defining separate relationships:
https://github.com/HMIS/LSASampleCode/blob/055d75259508e2acf86926f93b1757f54d28a5b8/LSASampleCode.sql#L2402-L2408
Removing the dateadd in the where clause and defining separate criteria for each relationship eliminates the -1s without impacting the other day counts:
https://github.com/HMIS/LSASampleCode/blob/896bf1f19b51a6faaa4deacb9f46e5ba34999370/LSASampleCode.sql#L2447-L2460
