### ISSUE TITLE
*** 7.6.2 - impossible "hhid.ExitDate is null" condition in the Sample Code ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#559]
@MollyMcEvilley 

![image-20200915-104344](https://user-images.githubusercontent.com/20728145/94101704-3ebaf780-fde5-11ea-9d33-f1676e1100de.png)

`when hhid.ExitDate is null` is never true because:

- `possible.ExitDate <= hhid.ExitDate `so `hhid.ExitDate` cannot be null
- and “possible” is INNER joined

**Comment by MollyMcEvilley** [comment]
This is a valid point -- the condition is not possible -- but it didn't impact the output.  On the other hand, I am extremely grateful to have examined this section in detail, because there was a big bug.  In the original code shown above, only hhid.EntryDate and hhid.ExitDate were being inserted to sys_TimePadded -- and hhid is only the qualifying exit.  
This statement has to insert possible.Entry/ExitDates or we miss all enrollments prior to the qualifying exit.  (Commit forthcoming.)
