### ISSUE TITLE
*** 6.12.2: "Cohort = 1" is not specified in the spec ***

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#560]
Sample code uses `Cohort = 1` but `Cohort` is not mentioned in the spec.

**Comment by MollyMcEvilley** [comment]
The cohort in sys_TimePadded isn't relevant to the business logic, but it's required in the sample code because the sample code creates sys_TimePadded with the Cohort column as non-nullable.     (There are other aspects of the sample code -- like the Step columns and ref_Populations -- that are handled in the same way.)
