### ISSUE TITLE
5.14 - AHARRRH (Move In Date) LSA_Person

### ISSUE THREAD

**Issue by jbloescw** [abtassociates/LSASampleCode#563]
![Snag_392d479d](https://user-images.githubusercontent.com/44415627/94319014-5dd59880-ff4f-11ea-96e7-1321ad94d8e5.png)

I'm seeking clarification on if something is a flag or a code/specs issue.

I have a few individuals that are in project type 13 and things seems to be breaking down in 5.14.
I've ran the code section by section to monitor the updates to these folks and they are getting set as a -1 for the AHARRRH field due to not having a move in date in #tlsa_Enrollment.  They move through sections 5.12 and 5.13 fine since they are not HoH.  They are regular adults in an AO or AC household type.

Since now that AHARRRH is now -1, section 5.15 then sets them as AdultRRH of -1.

What am I missing here?  The person is in an RRH type program, but since they don't have a move in date they do not get categorized as being an adult.  

Any clarification would help.

**Comment by TanyaPieterse** [comment]
Hi,
We have the same issue, the Flag file causes 8 distinct Flags with our data, for 8 fields (Gender, Ethnicity, Race, VetStatus, DisabilityStatus, DVStatus, CHTime, CHTimeStatus).  

The value in LSAPerson cannot be -1 where AdultEST=-1 and AdultRRH=-1 and AdultPSH=-1 and HoHEST=-1 and HoHRRH=-1 and HoHPSH=-1

**Summary of how it happens:**

- 5.3/5.4 sets HoHAdult=1 (Adult) and for example Gender=1 or 2  

- 5.12  sets HHTypeRRH to either 1/AO or 2/AC (Because they are active in ProjectType=13)

- 5.13 sets HoHRRH=-1 (Because they are not the HoH) 

- 5.14 sets AHARRRH=-1 (Because none of the clients have a MoveInDate)

- 5.15 sets AdultRRH=-1 (Because AHARRRH=-1)

In Step 5.15 - Because **'lp.HoHAdult not in (1,3) or lp.AHARRRH = -1'**, AdultRRH will be set to-1; BUT this means AdultRRH is being set to -1 on records where we have Adults with values for example for Gender.  And because HoHRRH=-1 and AdultRRH=-1 the HDX will kick out a Flag for records wtih values other than -1 in these 8 fields.

**Suggestion:**
Can we add a clean-up script just before the data is inserted into Step 5.19 LSAPerson that will set these values to -1 for all records where AdultEST=-1 and AdultRRH=-1 and AdultPSH=-1 and HoHEST=-1 and HoHRRH=-1 and HoHPSH=-1?

Thanks!
Tanya Pieterse

**Comment by MollyMcEvilley** [comment]
**AdultEST**, **AdultRRH**, and **AdultPSH** are subsets of **AHAREST**, **AHARRRH**, and **AHARPSH**, respectively.  It isn't valid to assume that they identify all adults included in the LSA.

Any/every flag that compares the values in **AdultEST/RRH/PSH** to any other value should be reviewed to ensure that it's consistent with the meaning of those columns.

**Comment by AzimShivji-Abt** [comment]
No, the error is in the Adult variables. They are not supposed to be limited to the AHAR universe.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by cwanska** [comment]
The flags have been edited to suppress this validation for the 2019/2020 upload cycle. We will revisit the issue when updating the specs and sample code for the 2021 upload cycle.

**Comment by MollyMcEvilley** [comment]
FY2021 specs:

    Redefined AdultEST/RRH/PSH to include all LSA adults.
    Added AHARAdultEST/RRH/PSH, which is limited to AHAR adults.
