### ISSUE TITLE
Step 5.14 (ties in with Ticket #563 and #564) - Causes Flags 141, 142, 143

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#565]
Hi,
Looks like Step 5.14 will set: 

- AHAREST=-1 if the client is exited on ReportStart 
- AHARPSH=-1 if the client is exited on ReportStart or the MoveInDate is null 
- AHARRRH=-1 if the client is exited on ReportStart or the MoveInDate is null 

(These are all Adult Clients in our data set)

Then Step 5.15 will set:

- AdultEST=-1 because AHAREST=-1
- AdultPSH=-1 because AHARPSH=-1
- AdultRRH=-1 because AHARRRH=-1

Because Step 5.12 sets HHType based on just the ProjectType and Active=1;   we have records where: 

- HHTypeEST=1 (AO)
- HHTypeRRH=1 (AO)
- HHTypePSH=1 (AO)

This causes HDX Flags 141, 142, 143.  Because the Flags compare HHTypeEST=AO with AdultEST which is set to -1 (same issue with RRH and PSH).

I think the issue is in the way Step 5.15 uses AHAREST, AHARPSH and AHARRRH to set the Adult columns to -1 in the cases where we do have Adults.

Thanks!

**Comment by michelleogburn** [comment]
Confirming Bitfocus is having the same issue, @cwanska .

**Comment by MollyMcEvilley** [comment]
This is a problem with the flags.

**Comment by AzimShivji-Abt** [comment]
No, the error is in the Adult variables. They are not supposed to be limited to the AHAR universe.

**Comment by nataliesus** [comment]
Hi, Here is Flag 143:
### Spec
According to the spec (section 5.15) and sample code, AdultPSH should have ActiveAge between 21 and 65 and all restrictions from 5.14.

![image](https://user-images.githubusercontent.com/28144855/94925585-1f4c5a80-04c8-11eb-9750-9216480115ae.png)


Please pay attention that **MoveInDate** cannot be null. Otherwise, both **AdultPSH** and **AHARPSH** would be **-1**.

### Live Example
Client (HoH, adult) has individual enrollment with parameters:

- n.ProjectType = 3
- n.EntryDate = 3/30/2018 
- n.ExitDate = null
- n.MoveInDate = null
- n.Active = 1
- n.ActiveAge = 44
- hhid.ActiveHHType = 1

 

The reason why this client is reported in Flag 143 is because:

- MoveInDate = null and, as a result, **AdultPSH = -1**
- but it is still PSH program so **HHTypePSH** = hhid.ActiveHHType **= 1**

### Issue
Either validation system should be fixed, or both spec and sample code should include or MoveInDate = null option for AdultPSH and AHARPSH and maybe some other parameters.

**Comment by AzimShivji-Abt** [comment]
Yes, the Specs are wrong. The Adult variables were never intended to be limited to the AHAR universe.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by cwanska** [comment]
The flags have been edited to suppress this validation for the 2019/2020 upload cycle. We will revisit the issue when updating the specs and sample code for the 2021 upload cycle.

**Comment by MollyMcEvilley** [comment]
FY2021 specs:

    Redefined AdultEST/RRH/PSH to include all LSA adults.
    Added AHARAdultEST/RRH/PSH, which is limited to AHAR adults.
