### ISSUE TITLE
Flag 680: Number of rows in LSACalculated sharing these parameters

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#572]
Hi,
With our dataset, it looks like Steps 8.5 and 8.6 will create 2 rows in the LSACalculated file that shares the same parameters, this causes the HDX to create Flag 680.

select * from lsa_Calculated where Cohort=-2 and Universe=2 and HHType=0 and Population=0 and SystemPath=-1 and ReportRow=23

We use the Sample Code verbatim, honestly I am not 100% sure how to change these steps to prevent the Steps from creating 2 rows with the same above parameters...

Thanks!
![image](https://user-images.githubusercontent.com/44713006/94734441-3d368580-0337-11eb-9630-0abc22e7d87d.png)

**Comment by MollyMcEvilley** [comment]
ReportRow 23 should only be produced by step 8.6.

The issue here is that 8.5 wasn't updated in the specs or the code to take into account new values in tlsa_Exit.**ExitFrom**, which split out RRH and PSH into 'not housed' and 'housed' groups.  8.5 code generates the **ReportRow** value based on **ExitFrom** + 16 but that doesn't work with the new values. 

To address this, changes are needed in 3 GitHub files (commits forthcoming) -- but _**the issue won't be fully resolved until changes are incorporated into the HDX and whatever SAS code generates the flags**_.  Changes here are:

1. Dictionary (list 33/**ReportRow**) - add report rows 63 (exit from RRH not placed in PH) and 64 (exit from PSH not placed in PH)
2. Specs section 8.5 - logic associated w/ additional report rows
3. Sample Code step 8.5 - code needed to produce additional report rows.

Assigning this to Cicely for HDX/flag changes (with note that related changes will be required for STELLA).

**Comment by MollyMcEvilley** [comment]
Removing the labels for sample code and specs because those issues have been addressed...

**Comment by cwanska** [comment]
Flags updated. Closing issue.
