### ISSUE TITLE
Flag 347: If CHTime equals 365, then CHTimeStatus cannot be -1 or 99

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#573]
Hi,

- In our tlsa_Person file, we have a few PersonalID's for whom Step 5.10 sets CHTime=365 and CHTimeStatus=3.  

- Then depending on the Living Situation fields (either missing or incorrect); Step 5.10.5 will update CHTimeStatus to 99.

Since CHTime=365 and CHTimeStatus=99; the HDX will create Flag 347 - stating that CHTime cannot be 365 if CHTimeStatus is -1 or 99.

Is the solution to try and fix the data so that the LSA Upload will work, or should the code be changed to set CHTime to -1 if we update CHTimeStatus to 99?

Thanks!

**Comment by MollyMcEvilley** [comment]
There was a conflict in the specs between the table of valid value combinations for **CHTime**/**CHTimeStatus** (does not include 365/99) and the business logic (will result in 365/99 under some circumstances).

The business logic is correct; adding the value combination to the table and assigning this to Cicely because it will require an update to the HDX checks.   
![image](https://user-images.githubusercontent.com/6156815/94792557-23348b80-03a7-11eb-9bf5-17604a286b9a.png)

**Comment by MollyMcEvilley** [comment]
Removing the 'specs issue' label because that issue has been addressed...

**Comment by cwanska** [comment]
Flags have been updated. Closing issue.
