### ISSUE TITLE
* 9.1 - MoveInDate discrepancy *

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#575]
A correction caused by #497 introduced a new issue.

### Scenario
If a Household has 2 HoHs with different `MoveInDate`, then `hhinfo` left join return 2 rows for the Household.

And because for `insert into dq_Enrollment` there is no GROUP BY, the same `n.EnrollmentID` will be inserted **twice for each MoveInDate.
![image-20201002-134608](https://user-images.githubusercontent.com/20728145/95086831-cb16c580-06d5-11eb-916c-863546d490a1.png)
**

**Comment by kcourtneywellsky** [comment]
We are seeing the same issue in some of our client data. We think the solution could be left outer joining hhinfo to hmis_Enrollment on EnrollmentID instead of HouseholdID. We are not certain that change meets the specifications, though.

**Comment by MollyMcEvilley** [comment]
There's no conflict with the specs in joining on _EnrollmentID_ instead of _HouseholdID_, and this is the kind of DQ issue that we are looking for (but I didn't think to look for).  I'll push out an update to the sample code later today as shown below with a note that the update is only needed in systems where it's possible to have more than one HoH and more than one _MoveInDate_ per _HouseholdID_.

![image](https://user-images.githubusercontent.com/6156815/96907091-c5a4d380-1468-11eb-82dc-78e9ed44a566.png)

**Comment by michelleogburn** [comment]
@MollyMcEvilley This issue is the same as reported by @eanders on #609 .

**Comment by eanders** [comment]
Thanks for connecting the dots @michelleogburn!  @MollyMcEvilley, did a code push for this get pushed?
