### ISSUE TITLE
LSAExit (4.40) Ever served in CoC vs. most recent location

### ISSUE THREAD

**Issue by ericwilka** [abtassociates/LSASampleCode#60]
In step 4.40, the specs say that qualifying exits must have the last record of EnrollmentCoC = ReportCoC.  It looks like in the sample it is only looking if they have ever been served in the ReportCoC based on the piece below:
inner join hmis_EnrollmentCoC coc on coc.EnrollmentID = hhinfo.EnrollmentID
						and coc.CoCCode = rpt.ReportCoC

Is it expected that the qualifying Exit query should have a different EnrollmentCoC criteria than the other activity part? 
 
This looks like Stat, ReturnTime, and SystemPath look for if an enrollment was ever in the ReportCoC as well.  Should Exit Data have an across the board approach to look at enrollments only where the most recent EnrollmentCoC record = ReportCoC or if any EnrollmentCoC record = ReportCoC?  Or will there be slight differences based on the question/step?

**Comment by TimLawrencePCL** [comment]
If you look at the last few lines of 4.7 in the sample code, you'll see where it's filtering records so we only include those for which the latest location matches the report COC.  So by the time you reach sections 4.40 etc. there shouldn't be any need to filter again.   Have a look and let us know if that doesn't seem correct.

**Comment by ericwilka** [comment]
Hi Tim,

That section only applies to the insert into active_households.  For 4.40 - 4.46 the sample code is going back to hmis_EnrollmentCoC.  I'm not sure if those are the lines you're referring to.  All of the sections in 4.40 - 4.46 use an INNER JOIN for any record in hmis_EnrollmentCoC that matches the ReportCoC.

Looking at the specs it seems that 4.40 might be using 2 different types of criteria as the section defining which enrollments to consider as potentially qualifying have the latest record condition.  The other activity section doesn't specify, so that makes more sense to do an any record match. 

4.41 looks like it assumes the latest record criteria from 4.40.
4.43 looks for future enrollments for Return time where the Entry EnrollmentCoC Record = ReportCoC
4.45 (Stat) and 4.46 (SystemPath) don't provide conditions in specs.  Not sure if those should be the any matching record or latest record.

**Comment by TimLawrencePCL** [comment]
Hi, Eric.  You're right.  I'm working on getting clarification on this.

**Comment by MollyMcEvilley** [comment]
This is a messy one.  

I committed changes to 4.40 and 4.43 to align the sample code with the requirements for EnrollmentCoC defined by the specs.

Section _4.46 Set SystemPath for Exit Cohort Households_ of the specs refers to the SystemPath logic defined for tmp_Household and only lists aspects of the logic that differ.  In retrospect, that was not a good idea -- omission of criteria that are identical to those for tmp_Household is confusing and will be addressed in LSA v2.0.  In the interim,  the requirement in the sample code that CoCCode for system path enrollments must = ReportCoC is consistent with the logic for tmp_Household in section 4.32 of the specs (and the original intent), so I'm leaving it alone.

In _4.45 Set Stat for Exit Cohort Households_, the specs don't say anything about EnrollmentCoC for prior enrollments AND they don't refer back to the logic for tmp_Household (which requires that the most recent EnrollmentCoC for any prior enrollment must equal ReportCoC).  I updated the sample code so that the criteria align with the tmp_Household logic (which was the intent) and identified the change as optional for vendors given that it's not in the specs.
