### ISSUE TITLE
*** Flag 533: LSAExit (Upload Error) ***

### ISSUE THREAD

**Issue by Ladvien** [abtassociates/LSASampleCode#600]
The SystemPath field in LSAExit must equal 2 (TH) if the household exited from TH (as reported in the ExitFrom field) and if the Stat field does not equal 5 (continuously engaged). The following row in your LSAExit file violates that rule.

SystemPath | 6 (TH + RRH only) | ExitFrom | 3 (TH) | Stat | 1 (Engage with continuum for first time or after at least 730 days inactive)
-- | -- | -- | -- | -- | --

Client has 3 enrollments:
![image](https://user-images.githubusercontent.com/6241517/95482220-7e402280-0953-11eb-9b3b-7b1a5514bb44.png)

QualifyingExitHHID= 20500
* Section 6.18
** SystemPath = 6
* Section 7.2.3
** ExitFrom = 3 ( because QualifyingExitHHIDhas ProjectType = 2) 
* Section 7.5
** Stat = 1

![image](https://user-images.githubusercontent.com/6241517/95482295-96b03d00-0953-11eb-8089-cc0de6ee64a6.png)

Cannot see issue in the results, so maybe the issue in the validation system?

**Comment by MollyMcEvilley** [comment]
Sending this over to @cwanska for flag review.  The info submitted is accurate -- if a household has enrollments in other project types that fall entirely within the date range of the enrollment with the qualifying exit, the logic defined by the specs for LSAExit will result in a path that includes those other project types, even when Stat in (1,2,3,4).  

I'm not sure how this didn't come up last year.  The flag may be new.

There _was_ a section in last year's specs identified as optional that said that **SystemPath** _could_ be set based solely on **ExitFrom** when **Stat** in (1,2,3,4) rather than building a complete history of system use.  There is currently an UPDATE statement in the sample code for section 7.7 -- also identified as optional -- that does this.  I'm going to delete that 'optional' statement -- commit forthcoming -- since the optional section was deleted from the specs.  (TBH, the specs last year and the optional statement in the sample code were there because we didn't consider the possibility of the situation that raised this issue.)

**Comment by cwanska** [comment]
@Ladvien Molly is pushing a code change today and the AHAR team will also be reviewing the logic on the flags.

**Comment by cwanska** [comment]
These flags will be suppressed for this round of data collection until the underlying questions about how to update specifications can be examined more closely.  The specifications will not be changed for the FY19 or FY20 data collection cycles.

**Comment by michelleogburn** [comment]
@MollyMcEvilley , we never included the optional code, but are still getting the flag. Suspect there is another reason for the flag. 

Noting from our discussion this morning. The flag is still being generated in error, thus why it is being suppressed.

**Comment by cwanska** [comment]
Flag has been suppressed for 2019/2020 upload period and specs will be reevaluated for 2021.

**Comment by MollyMcEvilley** [comment]
It is possible that a SystemPath would include more than one project type even when Stat = 1.
