### ISSUE TITLE
Flag 779 and 848 - Possible issue with step 8.21

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#618]
Good morning,

In Step 8.21 there is a left outer join to 'hmis_Enrollment hoh' where RelationshipToHoH = 1; but it does not filter out to just count missing CoCCodes for the HOH.  In our one dataset it therefore counts 91 clients without a CoCCode (those that are not the HOH and for whom a CoCCode is not entered).

In Step 9.2 where NoCoC is calculated it only looks at the hmis_Enrollment records where RelationshipToHoH = 1; therefor we have 0 as a count for HOH with a missing CoCCode.

Should Step 8.21 be an inner instead of a left outer join so that it only looks at the HOH records like the DQ Step?  Flag 779 is indicating that more clients in 1 year period in LSACalculated has a missing CoCCode than reported in the NoCoC column for the 3 year period.  Then Flag 848 shows the 'detail' of the Projects with the clients with missing CoCCodes.

Thanks!

**Comment by MollyMcEvilley** [comment]
The count in 8.21 is of _HouseholdIDs_ where there is no _CoCCode_ for the HoH... The coccode subquery is joined to the hoh subquery, so the count will include _HouseholdIDs_ that don't have a designated HoH (which is reasonable because the net effect of no HoH is that there is no record of _CoCCode_ consistent with the data standards), but unless I'm missing something here, it shouldn't count any client or household where there is a designated HoH with a _CoCCode_.   

(It is possible that I'm missing something -- if so, please re-open this and let me know what it is...)
![image](https://user-images.githubusercontent.com/6156815/100005813-8c2cf400-2d97-11eb-8cff-3368c541cbd6.png)

**Comment by MollyMcEvilley** [comment]
Oh oh oh!  
The left outer join to hmis_Exit was only including ExitDates after ReportStart, so hoh and coccode would be NULL for every household with an exit before ReportStart.  There is a commit forthcoming to remove this bit:
![image](https://user-images.githubusercontent.com/6156815/100017328-b935d280-2da8-11eb-8c9f-1af88d6534ed.png)

**Comment by TanyaPieterse** [comment]
Hi Molly,

Thanks!  I removed that highlighted part from Step 8.21 and it seems I still have 14 Households that are identified as having a missing Client Location CoC Code - you are correct thanks for explaining that join, it makes more sense now.  

Of those 14 Households: 
- 1 Household has an issue with the Information Date of the CoC Code on the HOH record that the CoC will need to fix.  This is also correctly identified in Step 9.2 in the NoCoC DQ column.  Since NoCoC only looks at the HOH records, it makes sense that just that one Household with the CoC Code issue is identified.  
- 13 Households has no designated HOH record, and therefore the CoC Code is missing, BUT here is my issue now, should these not also be identified by Step 9.2 in the NoCoC DQ column?  Or at least in the NotOneHoH1 and NotOneHoH3 DQ columns since there are no HOH designated?  Both NotOneHoH1 and NotOneHoH3 calculates to 0. 

Thanks!
