### ISSUE TITLE
LSA Flag ID 801, 804

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#622]
There is a conflict with these flags. 

Project File	801	1	Error	Project	Project	This project is missing a Housing Type.
Geography	804	1	Error	ProjectCoC	Project	This project is missing from your ProjectCoC file.

It is correct the project ID is missing from the Project and ProjectCoC files... however it is included in Calculated.csv.

This relates to section 8.20 of spec for ReportRow 61 where it clearly states it may include ProjectID that are not included in Project.csv.

![image-20201116-105445](https://user-images.githubusercontent.com/20728145/99592324-ee0ae980-29a4-11eb-819f-3a1d677e3d54.png)

Therefore, there is a problem either with the flag or the specs.

**Comment by MollyMcEvilley** [comment]
Michelle, are you getting these flags related to HousingType and ProjectCoC for records where the ProjectID is missing from the Project.csv file?

**Comment by KAdlerCW** [comment]
Per the discussion on the office hours call, we are receiving errors 801/804 in data sets where the project is not included in project.csv. An example of this is for CoC TX-500, Upload ID 1094, upload name, Test - 1 version 2, upload date 11-18-2020. I can provide the file if needed. 

In this data set, 20 project IDs are flagged, none of them are in Project.csv. Only 3 of the programs were actually missing HousingType (that was rectified after these flags were generated).

**Comment by michelleogburn** [comment]
@MollyMcEvilley 
Yes, the problem is the project is missing from Project.csv and ProjectCoC.csv because the operating end date is before the LSA reporting start date. 

However, there are enrollments, that are missing bed nights, that are within the CohortStart and CohortEnd period and are being reported as a Data Quality Problem, section 8.20, so the projects are listed in Calculated.csv.

But when the analysis goes to get project information about these projects, with data quality problems, the project doesn't exist in the Project.csv or ProjectCoC.csv... so it is throwing an error flag.

Clear as mud?

**Comment by eanders** [comment]
We are seeing 801 as well for projects with operating end dates prior to the report start.

**Comment by michelleogburn** [comment]
This was reported by Marin County, CA-507 as an example. Specifically project id 79.

**Comment by jessejorstad** [comment]
Thank you all for your patience.

We have confirmed that there are instances where the flag is identifying a ProjectID in LSACalculated.csv and then searching for that ProjectID in Project.csv (flag 801) or ProjectCoC.csv (flag 804), even though the sample code excludes that ProjectID from Project.csv/ProjectCoC.csv (because the project ended prior to ReportStart). The team will review this issue and adjust accordingly for next year. 

For this year, if the ProjectID that is triggering the flag is only seen in a row in LSACalculated for cohort 20 communities should submit a note to their data liaison through email confirming that the project is closed and there are no outstanding enrollments. The liaison will retain that note for the usability review. Note: if the ProjectID triggering the flag has enrollments in cohort 1 then this explanation will not be accepted as LSACalculated is reporting there were active records during the reporting period.
