### ISSUE TITLE
Flag 779 -- Possible issue with 8.21

### ISSUE THREAD

**Issue by 2008zjqc** [abtassociates/LSASampleCode#624]
Good morning,
The flag 779 is for 'You reported more cases of missing client locations in the one-year report period (in your LSACalculated data for ReportRow 62) than in the three-year period including the report year and the prior two years (in the NoCoC field of your LSAReport data).'

We believe there are some issues in step 8.21. One issue has been pointed out in issue #618. 
Another issue in step 8.21 that causing to generate those enrollment not within date range as follows:
'left outer join hmis_Exit hx on hx.EnrollmentID = hn.EnrollmentID 
		and hx.ExitDate >= rpt.ReportStart'

This part, for those exited enrollment which exited prior than report start. this part with return nothing.

In the where part in step 8.21

'and (hx.ExitDate is null or 
				(hx.ExitDate >= rpt.ReportStart and hx.ExitDate > hn.EntryDate))'

For those exited prior to report start, it always be true due to first condition 'hx.ExitDate is null '.

As a result, these 8.21 section, it intends to grab those exited enrollment within date range, in practical it can't due to the above reason. 

Please take a look. Thanks.
Best,
Chen

**Comment by MollyMcEvilley** [comment]
Thank you thank you!  I am removing the "hx.ExitDate >= rpt.ReportStart" criteria from the left join to hmis_Exit.  (commit forthcoming)

**Comment by MollyMcEvilley** [comment]
LSAReport.**NoCoC** is a three year count of households in LSA project types (not limited to lsa_Project) operating in ReportCoC that HAVE a head of household who doesn't have a valid EnrollmentCoC record.
LSAReport.**NotOneHoH1**/**3** counts households in the ReportCoC that do not have exactly 1 HoH

LSACalculated.**ReportRow** 62 counts households active the report period in an LSA project without a valid EnrollmentCoC record -- regardless of whether it's because there is no HoH (an EnrollmentCoC record is only valid when it's associated with the HoH) or because there just isn't an EnrollmentCoC record, or both. 

If there is an enrollment with no HoH and no CoC record:

- It won't get counted in **NoCoC** because there's no HoH.
- It won't get counted in **NotOneHoH1/3** because there's no CoC.
- It WILL get counted in ReportRow 62

As such, it is possible -- consistent with the specs -- that there might be "more cases of missing client locations in the one-year report period (in your LSACalculated data for ReportRow 62) than in the three-year period including the report year and the prior two years (in the NoCoC field of your LSAReport data)."  

This is probably something that should be reviewed for next year's specs, but for now I'm going to assign this to Cicely and flag it for AHAR team review so they are aware that flag 779 is being generated for valid records.

**Comment by cwanska** [comment]
The flag is working as expected. We will incorporate this into the normal review for next year.

**Comment by MollyMcEvilley** [comment]
FY2021 Specs - Aligned the parameters for row 62 and NoCoC so that they are looking at the same DQ issue --

- Row 62 by ProjectID in the report period
- NoCoC systemwide for the 3 year DQ period.

Project.csv parameters have been expanded to include all projects active since 10/1/2012, which should address any issues of ProjectID in LSACalculated not being in Project.csv.
