### ISSUE TITLE
Flag 528 - Spec Problem

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#640]
Issue Text:

> There is a discrepancy between the HHType field and the HHAdultAge field of your LSAExit file. In the HHType field, you reported that the households in this row were neither AO (adult-only) nor AC (adult-child) households. Yet you reported in the HHAdultAge field that they were AO or AC households.

HHAdultAge | 25 (At least one adult is 25 or older; at least one is under 55) | HHType | 99 (UN (unknown))
-- | -- | -- | --

### Problem

Step 3.4
![image-20201208-105754](https://user-images.githubusercontent.com/20728145/101724548-b3581680-3a63-11eb-93ce-447199db924c.png)

But there is no `ExitDate > ReportEnd` condition in the sample code! We followed the spec, which caused a problem that is now corrected... but the spec should be corrected for others.

**Comment by MollyMcEvilley** [comment]
I'm leaving this open because I think I must be missing something...

I don't understand the relationship between the **HHAdultAge/HHType** flag and setting the tlsa_Enrollment.**ExitDate**?

The sample code leaves the **ExitDate** null in step 3.4 if the _ExitDate_ in HMIS is after **ReportEnd**
![image](https://user-images.githubusercontent.com/6156815/102518513-64137680-405f-11eb-84c0-d4016ee63928.png)

**Comment by michelleogburn** [comment]
@MollyMcEvilley , we fixed this on our end. Closing this ticket.
