### ISSUE TITLE
Flag 822 - Need formulas

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#650]
Similar to Flag 845 (Issue #649) , we'd like to know the formulas used for this warning flag.

Also, seems it would be more appropriate to have this be a CoC flag.

**Comment by bayboos** [comment]
I don't know if that would help, but here's what I came up with when investigating this flag for one of our customers:

-----

In the investigated case, the flag file says there’s a difference in geography type for unknown household type in EST programs (ES/SH/TH) reported in LSACalculated vs LSAHousehold. Specifically, **LSAHousehold says 50% urban/50% suburban**, while **LSACalculated says 66.67% urban vs 33.33% suburban**.

The first suspicious thing is that one proportion suggests the total is divisible by 2 while the other suggests total divisible by 3. This is not impossible (obviously), but there are only 2 UN EST households in the LSAHousehold table. Sure enough, one is classified as living in urban area, while the other lives in suburban area - so the LSAHousehold part of the calculation is a match:

 

```
select hohid, hhtype, firstentry, lastinactive, eststatus, estgeography from tlsa_household where hhtype = 99 and eststatus <> 0;
       hohid       | hhtype | firstentry | lastinactive | eststatus | estgeography
-------------------+--------+------------+--------------+-----------+--------------
 485bd4-22aa-265ab |     99 | 2020-03-24 | 2020-03-23   |        22 |            1
 485783-d374-49fab |     99 | 2019-11-12 | 2019-11-11   |        22 |            2
```
 

Having only two such households means having the LSACalculated values divisible by 3 requires at least one of those to appear multiple times, which will become relevant later. Knowing that, I tried to decipher the LSACalculated part of the “equation”. 

As stated before, the description is vague so much that I can’t be 100% sure my thinking is correct; but this is what I came up with. We still are looking for UN EST households among the project-specific counts of distinct households in the LSACalculated table. The only reportrow that matches this description is reportrow 54, universe 10, populated in step 8.11. Using this as a selection criteria, assuming that the phrase “active in residence” refers to cohort 1, and adding UN EST conditions, returns 5 rows. This value is not divisible by 3, so there has to be some additional condition. Reviewing the returned records I’ve noticed that 3 rows have population = 0 while 2 rows have population = 5. Those populations do overlap (one is “all active in …” while the other is “Household with Disabled Adult/HoH”) so they can’t be used in combination for counting DISTINCT records. Population = 0 seems to be the right choice here since 1. it does include all households and 2. leaves us with 3 rows - exactly the number we are looking for (divisible by 3). Even though I can’t be sure that’s what the flag logic used, I will stick with this result.

Now the most interesting part begins.

With only 2 relevant records in LSAHousehold, having 3 in LSACalculated means one is being counted twice. I will not quote the entire query (because it’s too complicated, derived from step 8.11), but the result looks like this:

 

```
       hohid       | cohort | universe | hhtype | population | reportrow |            projectid             | geographytype
-------------------+--------+----------+--------+------------+-----------+----------------------------------+---------------
 485bd4-22aa-265ab |      1 |       10 |     99 |          0 |        54 | b54c73fed74442b9a55bb1e7075a4671 |             1
 485783-d374-49fab |      1 |       10 |     99 |          0 |        54 | b54c73fed74442b9a55bb1e7075a4671 |             1
 485783-d374-49fab |      1 |       10 |     99 |          0 |        54 | 12093dea5ee74c3994ea66c6dfb92d70 |             2
```
 

HoH 485783-d374-49fab is being counted twice, in different programs and geography types. This HoH have two enrollments in ES programs, both well within the report’s date range (2019-11-12 to 2020-01-06 and 2020-01-07 to 2020-06-30), present in both tlsa_hhid and tlsa_enrollment tables. At this point I’m not sure if that’s correct, however the focus point shifted to another piece of info provided in the flag’s description:

> We don't necessarily expect the two versions of the proportion to be exactly identical in all cases, but they should be close, especially because, in this case, **you did not report that the unduplicated count of households was lower than the sum of the project-level counts**--so one possible reason for the proportions to be different, that the **LSACalculated version is double-counting some heads of household, does not apply in this case**.

Something seems to be off because LSACalculated version is clearly double-counting one HoH. And that suggests the code is under-counting somewhere else. Unfortunately, it seems impossible to find one case of undercounting among 4404 distinct HoH/hhtype/projectID combinations grouped into 112 project-specific rows in the LSACalculated table. Especially since I wasn’t able to find a value this is being checked agains - the results of step 8.12.1 (“Unduplicated count of households by Project Type”), when applying the same filtering criteria (cohort = 1, population = 0) shows only 4256 distinct HoH/hhtype combinations - which IS “lower than the sum of the project-level counts”…

-----

FINAL NOTE: this particular WARNING flag was triggered because the differente appeared to be "too large" - calculated as 16% by the flag triggering logic. But in our case, this "seems to be too large % difference" was - in terms of absolute numbers - just ONE RECORD. You can't get the difference any smaller than that without getting rid of it entirely; therefore I believe that **if any difference is allowed at all, a difference of ONE RECORD should be allowed even if it appears to be large as a % of the total number of records**

**Comment by jessejorstad** [comment]
Is this useful?
![image](https://user-images.githubusercontent.com/75041695/104761622-06368500-5718-11eb-8473-c3baa3ee948e.png)

**Comment by nataliesus** [comment]
Hi @jessejorstad,

Could you please confirm/corrent that for lsa_Calculated we should look at rows where:
- Cohort = 1
- AND ReportRow = 54
- AND Universe = 10
- AND HHType = 0
- AND Population = 0
- AND ProjectCoC.ProjectType IN ( 1, 2, 8 )

Full percentage calculation formula would be very appreciated, I just cannot understand how they are calculated if i.e. the same [HoHID&HHType] can be counted in RowTotal calculation for different rows in lsa_Household table if ESTGeography or any other parameters from "group by ..." are different. 

We have 5 HoHID&ActiveHHType records in tlsa_HHID table with active enrollments in 2 Projects (Project Types are 1 and 2) where Projects have the same Geocode = 129017 but different address and different GeographyType. 
Please advise how to solve the issue if:
- for tlsa_Household.ESTGeography we use GeographyType from the most recent active project stay
- HoH's have active project stays in 2+ Projects with different GeographyTypes
![image](https://user-images.githubusercontent.com/28144855/105047384-ecc46e80-5a72-11eb-8f25-c5a0bf33b3e6.png)


Thank you!

P.S. I wonder if I prepared correct SQL query to calculate percentage because % are different from our flags file

SELECT 'lsa_Household' AS label,
       SUM( RowTotal ) AS total,
       SUM( IF( ESTGeography = 1, RowTotal, NULL )) AS urbanCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 1, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS urbanPerсentage,
       SUM( IF( ESTGeography = 2, RowTotal, NULL )) AS suburbanCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 2, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS suburbanPerсentage,
       SUM( IF( ESTGeography = 3, RowTotal, NULL )) AS ruralCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 3, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS ruralPerсentage,
       SUM( IF( ESTGeography = 99, RowTotal, NULL )) AS unknownCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 99, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS unknownPerсentage
  FROM lsa_Household
 WHERE ESTGeography > 0

 UNION ALL

SELECT 'lsa_Calculated' AS label,
       SUM( c.Value ) AS total,
       SUM( IF( pc.GeographyType = 1, c.Value, NULL )) AS urbanCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 1, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS urbanPerсentage,
       SUM( IF( pc.GeographyType = 2, c.Value, NULL )) AS suburbanCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 2, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS suburbanPerсentage,
       SUM( IF( pc.GeographyType = 3, c.Value, NULL )) AS ruralCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 3, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS ruralPerсentage,
       SUM( IF( pc.GeographyType = 99 OR pc.ProjectID IS NULL, c.Value, NULL )) AS unknownCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 99 OR pc.ProjectID IS NULL, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS unknownPerсentage
  FROM lsa_Calculated AS c
  JOIN lsa_Project AS p ON ( c.ProjectID = p.ProjectID )
  LEFT JOIN lsa_ProjectCoC AS pc ON ( p.ProjectID = pc.ProjectID )
 WHERE c.Cohort = 1
   AND c.ReportRow = 54
   AND c.Universe = 10
   AND c.HHType = 0
   AND c.Population = 0
   AND p.ProjectType IN ( 1, 2, 8 )
   
![image](https://user-images.githubusercontent.com/28144855/105057292-c0fab600-5a7d-11eb-9b0f-d1c6c167a54f.png)

**Comment by jessejorstad** [comment]
Hi Michelle, 
I am just seeing this now. I just pinged the AHAR team to take a look and will try to get you an answer. Thanks for your patience.

**Comment by cwanska** [comment]
A bug was found in the flag code and has been corrected. The latest flag run on Thursday 1/21 should show resolution of these flags. If the flag still appears, please confirm the geography type isn't misclassified.
