### ISSUE TITLE
Flag 837 (Warning)

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#653]
### Warning Text

> Unclassifiable households in ES/SH/TH (active in residence): There is a large difference in the unduplicated* proportion of households served in urban/suburban/rural areas, as reported in the ESTGeography field of your LSAHousehold file, and the duplicated* proportion of households served in urban/suburban/rural areas, as reported in your LSACalculated file. (* The unduplicated proportion is the simple proportion of households served in each geography type, measured across all households served in ES/SH/TH in your CoC. The duplicated proportion, however, is based on the project-level household counts from the LSACalculated file. Each ES/SH/TH project has a geography type you reported. We summed those project-level counts, among all ES/SH/TH projects, by geography type to compute this duplicated proportion. It is a 'duplicated' proportion because it would double-count heads of household served in the same household type in multiple ES/SH/TH projects. **It is possible that the difference between the unduplicated and duplicated geography proportions is due mostly to this double-counting**, but it is also possible that the geography type was misclassified in the LSAHousehold file, and that is why we are asking this question.)

UN HHs in ES/SH/TH (active in residence): LSAHousehold - Percentage of households in areas where the geography type is urban | 71.43%
-- | --
UN HHs in ES/SH/TH (active in residence): LSACalculated - Percentage of households in areas where the geography type you reported is urban | 60.00%
UN HHs in ES/SH/TH (active in residence): LSAHousehold - Percentage of households in areas where the geography type is suburban | 28.57%
UN HHs in ES/SH/TH (active in residence): LSACalculated - Percentage of households in areas where the geography type you reported is suburban | 40.00%

This flag is similar to Flag 845. Also seems to be a new flag. It's not an error, but a warning. The AHAR team confirms “It is possible that the difference between the unduplicated and duplicated geography proportions is due mostly to this double-counting” but they still want us to take a look? 

We aren't sure how to move on this. And like Flag 845, perhaps this would be better as a CoC flag.

**Comment by nataliesus** [comment]
Hi @jessejorstad,

About this issue. 

Flags file reports:
![image](https://user-images.githubusercontent.com/28144855/105332512-61b3b780-5bdd-11eb-9214-70d7bedb6b35.png)

We can reproduce the exact same values (SQL query can be found below):
![image](https://user-images.githubusercontent.com/28144855/105332708-9293ec80-5bdd-11eb-875c-4ac7ba567fa1.png)

10%-20% difference in percentage values is because the number of UN Households is very small (look at urbanCount and suburbanCount columns) and some Households are counted multiple times for LSACalculated.

Here are 10 not-unique Households that are counted for lsa_Calculated. **1 Household is counted 4 times** because of active enrollments into 4 different projects. So, if the flag counted unique Households, then we will not have any difference in percentage.

![image](https://user-images.githubusercontent.com/28144855/105334928-1c44b980-5be0-11eb-9f0f-c049f00bf69b.png)


We used next query to get percentage values:
``
SELECT 'lsa_Household' AS label,
       SUM( RowTotal ) AS total,
       SUM( IF( ESTGeography = 1, RowTotal, NULL )) AS urbanCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 1, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS urbanPerсentage,
       SUM( IF( ESTGeography = 2, RowTotal, NULL )) AS suburbanCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 2, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS suburbanPerсentage,
       SUM( IF( ESTGeography = 3, RowTotal, NULL )) AS ruralCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 3, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS ruralPerсentage,
       SUM( IF( ESTGeography = 99, RowTotal, NULL )) AS unknownCount,
       CONCAT( ROUND( SUM( IF( ESTGeography = 99, RowTotal, NULL )) / SUM( RowTotal ) * 100, 2 ), '%' ) AS unknownPerсentage
  FROM lsa_Household
 WHERE ESTGeography > 0
   AND HHType = 99

 UNION ALL

SELECT 'lsa_Calculated' AS label,
       SUM( c.Value ) AS total,
       SUM( IF( pc.GeographyType = 1, c.Value, NULL )) AS urbanCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 1, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS urbanPerсentage,
       SUM( IF( pc.GeographyType = 2, c.Value, NULL )) AS suburbanCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 2, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS suburbanPerсentage,
       SUM( IF( pc.GeographyType = 3, c.Value, NULL )) AS ruralCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 3, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS ruralPerсentage,
       SUM( IF( pc.GeographyType = 99 OR pc.ProjectID IS NULL, c.Value, NULL )) AS unknownCount,
       CONCAT( ROUND( SUM( IF( pc.GeographyType = 99 OR pc.ProjectID IS NULL, c.Value, NULL )) / SUM( c.Value ) * 100, 2 ), '%' ) AS unknownPerсentage
  FROM lsa_Calculated AS c
  JOIN lsa_Project AS p ON ( c.ProjectID = p.ProjectID )
  LEFT JOIN lsa_ProjectCoC AS pc ON ( p.ProjectID = pc.ProjectID )
 WHERE c.Cohort = 1
   AND c.ReportRow = 54
   AND c.Universe = 10
   AND c.HHType = 99
   AND c.Population = 0
   AND p.ProjectType IN ( 1, 2, 8 );
   ``

**Comment by cwanska** [comment]
This flag is simply asking the vendor/community to confirm there are no misclassified geography types.
