### ISSUE TITLE
Question regarding changes to 4.40

### ISSUE THREAD

**Issue by tcalder** [abtassociates/LSASampleCode#66]
See also #55 , #43 

In commit :https://github.com/HMIS/LSASampleCode/commit/71f4fc896329032e02f3bc4e424e8e32289441a6 a join to Exit data is made to ensure that someone is not counted twice (as an adult and child). However it appears that the change would exclude counting members of a household who have not exited for age calculations.

For example given a household where two people enter and then 6 months later person A exits but person B remains, When doing the age calculation for the Cohort where person A exits, Person B's age would not be considered. This is important because these ages are used to then calculate things like HHType. if Person B was a child it would mean that an AC household is incorrectly labled as AO.

**Comment by MollyMcEvilley** [comment]
This is a situation where the sample code assumes that source data is consistent with the HMIS data standards... specifically, the requirement that the HoH be present for the entire project stay.  In systems where it's possible for users to create records that aren't consistent, a workaround would be required.
 

![image](https://user-images.githubusercontent.com/6156815/48808816-257c2800-ecf0-11e8-9dd2-c9dade3e8e02.png)

**Comment by MollyMcEvilley** [comment]
In general, the specs and the sample code assume that HMIS data are consistent with Dictionary requirements. There are a few specific deviations from that basic assumption in the specs (e.g., modified logic for systems where it's possible that a Household ID might have <> 1 heads of household) and a few more in the sample code (e.g., those referenced in issue #34 and a check that MoveInDate is between EntryDate and ExitDate in section 4.14).  Those are issues that I got used to working around in VA Repository reporting code.

It would be impossible to anticipate all -- or even a majority -- of potential issues in HMIS data that I didn't encounter in the Repository because the upload validation process didn't allow them (or maybe never noticed).  I think the assumption HAS to be that HMIS programmers are familiar with the quirks specific to their own data and the best ways to deal with them in code.  

Having said that, I'm flagging this issue for review during the next data standards revision because I think the root of the issue is that the HMIS Data Dictionary isn't explicit about where _System Logic_ is intended to describe UI functionality that an HMIS should implement to ensure that data are compliant at the point of entry and where it might be more accurately described as _Data Collection Logic_ that users are expected to understand and comply with.

**Comment by ericwilka** [comment]
Hi Molly,

I think we'd still have the same question with a household that's consistent with the dictionary.  If the Adult HoH remains and a child leaves in a different Cohort, should each of those members be reported separately?  Is this expected result that it's an exit from AC HHType or AO HHType?

**Comment by MollyMcEvilley** [comment]
Good question! The easy part is that the child's exit would not ever be considered 'qualifying' -- even if the child exited alone in an earlier cohort from the HoH -- because the criteria for inclusion require that RelationshipToHoH = 1.  

HHType for the qualifying exit is based on HoH and HH members' ages as of EntryDate or CohortStart, whichever is later.  
- If the child and the HoH exit in the same cohort period, the child is relevant to HHType for the qualifying exit -- HHType = AC.

- If the child exits in an earlier cohort period, the child is not relevant to HHType for the qualifying exit -- HHType = AO.

**Comment by ericwilka** [comment]
That's a little different than what we're seeing in the specifications for section 4.40:
Household type (HHType) for each HMIS HouseholdID is based on the presence or absence of household members by age status – adult, child, or unknown. 

By only looking at the associations with the HouseholdID, then it would stay consistent with how type is calculated in all other household type calculations further down.  It would then match the way the HHType is being calculated in the Other Activity check of 4.40, 4.43 Return Time, 4.44 Household characteristics and HHAdultAge calculation, 4.45 for stat, and 4.46 for SystemPath, which looks at HouseholdID link regardless of when others exited. 

 We thought that because we aren't determining how far apart an exit is, it would be based on any association with the HouseholdID.  That way if there was a couple day difference then it would be reporting the HHType for the whole household.  Should the section with we INNER JOIN in CohortDates be moved to the subquery where we determine the exits for heads of household and a cohort date comparison after that?  Or couldn't the right CohortID be determined first and then calculate the age?

**Comment by MollyMcEvilley** [comment]
The circular reference that I just found in the specs doesn't help clarify the concept -- the 'exit' circled in red below should be 'active' -- but like the active cohort, HHType for the exit cohorts is based on household members' ages at the later of _EntryDate_ or _CohortStart_ (highlighted below)...
![image](https://user-images.githubusercontent.com/6156815/49113404-785f5d80-f263-11e8-9d4c-767e4337f391.png)

…and the HHType for other activity (in this section and the others you mentioned, as well as 4.29.b and 4.32) is based only on _EntryDate_: 
![image](https://user-images.githubusercontent.com/6156815/49113644-16532800-f264-11e8-8c0e-5b416858c92b.png)

I sympathize with frustration about multiple approaches to determining age for HHType.  Personally, I think it should always (in every HMIS report) be based on ages on the last date active in the report period; alas, persons who have the final authority on such decisions do not agree.  In any case, the differences were a deliberate decision on the part of the research team.

**Comment by ericwilka** [comment]
I'm not sure we're focusing on the same thing.  We're not looking for clarification for how to calculate age.  We're looking at which clients to include include when counting numbers of adults, children, and unknown household types after age has been calculated.  

In the section that was updated, it changed which clients to look at for the HHType calculation in a way that was different from the rest of LSAExit.

**Comment by MollyMcEvilley** [comment]
For the enrollments that get inserted into ex_Enrollment -- those with an exit in the cohort period and no other activity in the two weeks following -- clients who were active in the cohort period should be included.  

For the other activity -- including enrollments in the 14 days after exit (disqualifying), enrollments 15-730 days after exit (returns), and previous enrollments relevant to system engagement status and system path -- all clients associated with the HouseholdID should be included.

**Comment by MollyMcEvilley** [comment]
Thank you @ericwilka!  I was missing a key point:
- 4.40 gets exit cohort members and HHTypes based on the HoH and HH members who also exited in the cohort period.
- 4.44 sets population identifiers for the exit cohort households and should be based on the household composition relevant to the HHType -- i.e., the HoH and HH members who also exited in the cohort period -- and not (if they exist) household members who exited prior to CohortStart. 

[Committed a fix ](https://github.com/HMIS/LSASampleCode/commit/5f55a141779c0cbe6ef52e33bde8ad7edd777791
)
