### ISSUE TITLE
VictimServicesProvider in hmis_Organization should be VictimServiceProvider

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#664]
I believe this line which references hmis_Organization needs an `s` removed.
https://github.com/HMIS/LSASampleCode/blob/a01adee154e8dd7f95000a2d2828c476d90c0fb5/04_02%20to%2004_06%20Get%20Other%20PDDEs.sql#L20

**Comment by kiadso** [comment]
The code matches the LSA Specifications (plural), but the HUD CSV Export Specs say `VictimServiceProvider` (singular).

**Comment by eanders** [comment]
Since this is referencing the `hmis_Organization` table I think this should match the CSV spec. But maybe I'm missing something.

**Comment by MollyMcEvilley** [comment]
You are correct! I will update.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Please revert changes in LSA because, according to the most recent CSV FY2022 v1.1, field name should be VictimServiceProvider (not VictimService**s**Provider)

CSV FY2022 v1.1 spec: https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.1_clean.pdf
![image](https://user-images.githubusercontent.com/28144855/133433004-6aa31c96-05a9-4c74-8600-6e9782b5352b.png)

Also, LSA Programming Specifications FY2021.docx and LSA Programming Specifications FY2021 Annotated.docx should be updated with a reference to the most recent v.1.1 (not v.1.0 as it is not) of FY 2022 HMIS CSV Format Specifications:
![image](https://user-images.githubusercontent.com/28144855/133442151-f19023a1-6cfe-4f78-a644-5d87cf17f67b.png)

Best regards,
Natalie
