### ISSUE TITLE
Enrollments to Include in Section 4.45

### ISSUE THREAD

**Issue by nathanandrade74** [abtassociates/LSASampleCode#68]
Section 4.45 of the LSA report establishes the previous enrollment for each enrollment in the tmp_exit data construct. I noticed that in the sample output for tmpExit there are StatEnrollmentIDs for enrollments that are not active in any of the cohort dates. For example, EnrollmentID 580933 exited on 11/04/2013, meaning it is not active in any of the cohorts, but it is brought in as the StatEnrollmentID for EnrollmentID 586047. Based on the conversation we had during one of the previous office hours,I was under the impression that the data set for the report should only include enrollments that are active during one of the cohorts, is this not the case? If not, then should there be a cutoff date for this section? I just want to make sure we are including the right universe of enrollments for the report.

**Comment by MollyMcEvilley** [comment]
In the sample code -- and in the specs -- the hmis_ prefix before a table name refers to HMIS data in its entirety.  For example, in 4.7, active HouseholdIDs are selected from HMIS data in hmis_Enrollment, hmis_Exit, and hmis_Services.  This is the first step in identifying active enrollments, so the hmis_(table name) data is assumed to include all HMIS data.

If you are first creating and populating hmis_ tables from HMIS data in a system-specific structure in order to run the sample code, the initial selection of data INTO hmis_ tables:
- At a minimum, should include all enrollment data from the full HMIS that would, based on logic defined by the specs, be selected FROM hmis_ tables into intermediate tables at any point; or
- Could (more simply) include data related to all enrollments in ES/SH/TH/RRH/PSH active on or after 10/1/2012 and all SO enrollments with exits on or after ReportStart - 3 years.
