### ISSUE TITLE
Step 4.46

### ISSUE THREAD

**Issue by eanders** [abtassociates/LSASampleCode#69]
With the code current as of 11/28 (9am) we are still getting duplicate key errors for inserts into sys_Enrollment.

We have a client with two enrollments in ES, one as an individual and one as part of a family like so:

Family Enrollment: Apr 8, 2016 - Jul 1, 2016
Individual Enrollment: May 29, 2015 - Apr 6, 2016

The insert is then failing with the following because the individual enrollment is being returned as both active and inactive.

```
HoHID, HHType, EnrollmentID, ProjectType, EntryDate, MoveInDate, ExitDate, Active
xxxxxx,1,yyyyyy,1,2015-05-29,NULL,2016-04-06,1
xxxxxx,2,zzzzzz,1,2016-04-08,NULL,2016-07-01,1
xxxxxx,2,yyyyyy,1,2015-05-29,NULL,2016-04-06,0
```

I believe this is being caused by the client having two rows in the ex_Enrollment table (one for each enrollment) and two rows in tmp_Exit (one for each enrollment). This then causes the client to be both active and inactive in the following case statement.
```case when hn.EnrollmentID = ex.EnrollmentID then 1 else 0 end```

This appears to be a bug in the logic of the spec.  4.41 states that the combination of HoHID, Cohort, and HHType is the key for determining if the enrollment gets added to tmp_Exit.  Because the client is a head of household in two enrollments with differing HHTypes, they are assigned two rows in tmp_Exit.  The check then looks at EnrollmentID and not PersonalID, so one entry in tmp_Exit is active and the other not.  If the HouseholdID was used instead of HoHID for tmp_Exit, this would not be a problem because there are two distinct households.  Alternatively, the check to determine if the enrollment is "active" could be done against the PersonalID.  The former would end up with two rows in `sys_Enrollment` while the latter would end up with one.

**Comment by MollyMcEvilley** [comment]
1.  There were two separate sections numbered 4.46 -- combined them and re-ordered the steps follow along better with the specs description of the business logic.
2. Removed Active from the 4.46 INSERT to sys_Enrollment -- it isn't used later -- so that eliminated one reason an enrollment might get inserted twice, but left the issue with HHType.
3.  To address the HHType issue, split the INSERT to sys_Enrollment into two separate steps:
a. Insert enrollments associated with qualifying exits (HHType from tmp_Exit)
b. Insert enrollments prior to qualifying ExitDates IF the EnrollmentID isn't already in sys_Enrollment (HHType based on ages at entry.)

That prevents your EnrollmentID yyyyyy being selected with two different household types.  yyyyyy IS before EnrollmentID zzzzzz, and (at this point) potentially part of zzzzzz's SystemPath -- BUT we already know that it (because all qualifying exits) is followed by at least 14 days of inactivity and therefore CAN'T be part of a period of continuous service with a later enrollment.  

As a side note, if we release sample code with any future programming spec (personally, I am ambivalent), it is clear that the sample data set should be more comprehensive.
