### ISSUE TITLE
4.28 Commit that changes the logic of MostRecent enrollment

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#75]
Regarding this commit:
https://github.com/HMIS/LSASampleCode/commit/4c8f32999e633c9baee614f95870f5504336a125

There is this description:

> --CHANGE 11/27/2018 - incorporate identification of most recent
> -- active enrollment for use in setting EST/RRH/PSHGeography into 
> -- each UPDATE statement rather than using active_Enrollment.MostRecent.
> -- This follows the steps described in the specs more closely; it shouldn't 
> -- alter output but may improve performance

But the output was altered! Previously the most recent was the enrollment with most recent entry date and if there was two or more of them, the one with the most recent EnrollmentID. Now the order is:

`order by case when an.ExitDate is null then rpt.ReportEnd else an.ExitDate end desc, an.EntryDate desc`

Sample:
PersonalID: 36989

- Previous Logic
-- Most recent: Emergency Shelter - Entry/Exit Date - Project 3
- Current Logic
-- Most recent: Emergency Shelter - Night-by-Night - Project 2

So, which is the correct logic for determining most recent enrollment? The previous logic seemed to be more in line with the usual APR, etc. logic.

**Comment by MollyMcEvilley** [comment]
You're right.  The previous logic identified 'most recent' by looking for the latest entry date.  The current logic looks for the enrollment with the latest active date in the report period -- and that's what the specs require, so the change inadvertently fixed a bug. 
![image](https://user-images.githubusercontent.com/6156815/49442515-b692da80-f797-11e8-8aac-63820dc94247.png)
As highlighted above, the specs also require that geography records be dated on or before the last active date for the HoH, which was missing from the sample code.  The fix for that is in the commit above.
