### ISSUE TITLE
4.70 Error in Commit

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#76]
@MollyMcEvilley , it appears the latest commit has a problem.

`from lsa_report	rpt
inner join hmis_Enrollment n on n.EntryDate <= rpt.ReportEnd
inner join hmis_Project p on p.ProjectID = n.ProjectID
inner join hmis_Client c on c.PersonalID = n.PersonalID
left outer join hmis_Exit x on x.EnrollmentID = n.EnrollmentID 
	--CHANGE 11/8/2018 ExitDate >= ReportEnd (not ReportStart) - 3 years
	and x.ExitDate >= dateadd(yy, -3, rpt.ReportEnd)
inner join (select distinct hh.HouseholdID, min(hh.MoveInDate) as MoveInDate
	from hmis_Enrollment hh
	inner join lsa_Report rpt on hh.EntryDate <= rpt.ReportEnd
	inner join hmis_Project p on p.ProjectID = hh.ProjectID
	inner join hmis_EnrollmentCoC coc on coc.EnrollmentID = hh.EnrollmentID
		and coc.CoCCode = rpt.ReportCoC
	where p.ProjectType in (1,2,3,8,13) and p.ContinuumProject = 1
	group by hh.HouseholdID
	) hhinfo on hhinfo.HouseholdID = n.HouseholdID
--CHANGE 11/28/2018 add WHERE clause to limit to three years
where x.ExitDate is null or x.ExitDate >= dateadd(yy, 3, rpt.ReportEnd)`

Conditions
`left outer join hmis_Exit x on x.EnrollmentID = n.EnrollmentID 
	--CHANGE 11/8/2018 ExitDate >= ReportEnd (not ReportStart) - 3 years
	and x.ExitDate >= dateadd(yy, -3, rpt.ReportEnd)`

and
`--CHANGE 11/28/2018 add WHERE clause to limit to three years
where x.ExitDate is null or x.ExitDate >= dateadd(yy, 3, rpt.ReportEnd)`

Taken together, these don't do what is described in the comments above.

After first condition  x.ExitDate would be null for enrollments with exits previous to 3 years from report_end_date and enrollments without exits. After the second condition we take into account only such enrollments (but not enrollments with an exit in 3-year range before report_end_date) AND enrollments with exit 3 years after(!) report_end_date.  

This doesn't make sense.

**Comment by MollyMcEvilley** [comment]
You are correct -- It didn't make sense.

1. Join to hmis_Exit was excluding any information about ExitDates prior to (ReportEnd - 3 years) so...

2. WHERE clause couldn't exclude enrollments that exited prior to the relevant period AND

3. The typo in the WHERE clause -- ExitDate had to be >= (ExitDate PLUS 3 years), which is ridiculous, rather than ExitDate MINUS three years (which is correct).

Thank you -- fixed to include info about all ExitDates in the join to hmis_Exit and to evaluate them correctly in the WHERE clause.
