### ISSUE TITLE
Step 4.28b

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/LSASampleCode#78]
Step 4.28b:
This should not affect the output, but will be more consistent.
Currently: update tmp_Household set ESTGeography = null
Should be: update tmp_Household set ESTGeography=null, RRHGeography=null, PSHGeography=null

**Comment by MollyMcEvilley** [comment]
Thank you for pointing out the inconsistency!  I think that one is a stray that I missed deleting when I was working on the 11/27 change... it's not wrong that it's there  but I think I'd rather delete it than add the other project types because it should be okay to trust that those columns are null at this point in the sample code...   (It's not setting the LivingSituation or Destination columns to null.)
