### ISSUE TITLE
4.43, 4.45 Probably need a missing condition

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#80]
Our developer thought a similar condition needs to be added to these sections:
```
(x.ExitDate is null 
		or (x.ExitDate >= rpt.ReportStart 
			and (x.ExitDate > hn.EntryDate or
				(x.ExitDate = hn.EntryDate and hn.MoveInDate is null and p.ProjectType in (3,13))))
	) 
```
It is needed on 
4.43 Set ReturnTime for Exit Cohort Households
4.45 Set Stat for Exit Cohort Households

**Comment by MollyMcEvilley** [comment]
The same thing MIGHT apply to 4.40, but I am going to leave this one alone.  The specs don't require it and although using obviously flawed data for Stat and ReturnTime isn't ideal, an illogical relationship between EntryDate and ExitDate won't result in skewing reporting for the whole CoC as it would for the active cohort (e.g, negative length of stay).  
I am going to mark this issue to review for v2, however -- because I'd like to suggest to the research team that DQ reporting should include a count of enrollments in the three year period where Entry/ExitDates are illogical and a suggestion that the HDX should reject any upload where the number is greater than zero.
