### ISSUE TITLE
4.44 Set Population Identifiers

### ISSUE THREAD

**Issue by michelleogburn** [abtassociates/LSASampleCode#84]
I feel like we are in the middle of a not-so-fun game of whack-a-mole... here we go again with 4.44

Our developer found a couple of problems following one of the recent commits.

1) Here is a sample record from LSAExit with an issue
![image-2018-12-04-12-53-43-051](https://user-images.githubusercontent.com/20728145/49781113-5e436780-fcc6-11e8-8139-544d201e965f.png)

In the SQL related to determining the HHAdultAge, there is a condition:

```
) ageGroup on ageGroup.EnrollmentID = ex.EnrollmentID
			and (ex.HHType = 1
				or (ex.HHType = 2 and ageGroup between 18 and 24))

```
It should be updated to:

`... and ageGroup between 18 and 55`

Because in another case HH with adults and children, where adults are older than 24 would be excluded. According to the spec, it is an issue and the value should be set to 25 or 55.
![image-2018-12-04-12-56-12-646](https://user-images.githubusercontent.com/20728145/49781315-196c0080-fcc7-11e8-8b57-85a1da1cdb47.png)

The above sample client is 25+ years old in a household with a minor child. The output of the sample code is -1, but it should be 25.

---
2) in the same section

```
update ex
set ex.HHParent = 0 
from tmp_Exit ex
where ex.HHParent = 1 and ex.HHAdultAge not in (18,24)
```

The code includes a comment:

> – NOTE: HHParent value is preliminary – it is reset to 0 for AC
> – households with adults over 24 at the end of this section.
> 
> – CHANGE 10/15/2018 - child of HoH must be < 18 to set HHParent = 1

The developer can't find such a restriction in spec and it looks like that update would set HHParent = 0 for HH with HHType = 3 (childs only, HHAdultAge = -1)

**Comment by MollyMcEvilley** [comment]
1.  I don't think this is clear enough in the specs...  HHAdultAges over 24 for AC households aren't relevant in identifying any populations, so HHAdultAge can be -1 for an AC household UNLESS HHAdultAge is 18 or 24.  I'm leaving the sample code alone, but other values (25 and 55) won't be flagged as errors by the HDX, so they're not WRONG -- just not needed.  Flagging to make this clearer for v2.0. 
![image](https://user-images.githubusercontent.com/6156815/50229902-6318b300-0379-11e9-968d-0585ad85bb6e.png)

2. HHParent and HHAdultAge - correcting the code so that CO households don't lose their HHParent designation. 
![image](https://user-images.githubusercontent.com/6156815/50229488-6eb7aa00-0378-11e9-9ab6-b1d675cbea22.png)
